daralet-ac/ACE

Source/ACE.Entity/Enum/CombatAbility.cs
Source/ACE.Server/Entity/DamageEvent.cs
Source/ACE.Server/WorldObjects/Player_Combat.cs

20% chance to block attacks when using a two-handed weapon or dual-wielding

feat: replace riposte combat ability with parry

---

Source/ACE.Server/Managers/RecipeManager.cs

feat: disable tinkering recipes until crafting overhaul is complete

---

Source/ACE.Server/WorldObjects/Creature_Combat.cs

fix: disable secondary attributes for monsters

---

Source/ACE.Server/Command/Handlers/DeveloperFixCommands.cs
Source/ACE.Server/WorldObjects/Player_Skills.cs
Source/ACE.Server/WorldObjects/SkillAlterationDevice.cs

fix: prevent untrain skill removing heritage skills and allow it to remove defense skills

---

Source/ACE.Server/WorldObjects/Player_Skills.cs

fix: set correct player skills list

---

Source/ACE.Server/WorldObjects/Creature_Melee.cs

- fixes cleave so it no longer hits fully translucent or invisible monsters

fix: cleave

---

Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs

allows inqquest to check for solves across the entire account

feat: add account limited inqquest

---

Source/ACE.Entity/Enum/EmoteType.cs
Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs

creates emote to allow scripted setting of lb environ fogs etc.

feat: setlbenviron emote

---

Source/ACE.Entity/Enum/EmoteType.cs
Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
Source/ACE.Server/WorldObjects/Player_Xp.cs

-adds an emote type to relieve a set amount of vitae (current remove vitae emote removes all vitae, no matter how much)

feat-relieve vitae emote

---

Source/ACE.Server/Factories/LootGenerationFactory.cs
Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs

Also, adjusted Diminishing Roll function.

refactor: align armor mod code with new weapon mod code

---

Source/ACE.Entity/Enum/CharacterOption.cs
Source/ACE.Entity/Enum/CombatAbility.cs
Source/ACE.Entity/Enum/SpellId.cs
Source/ACE.Server/Entity/DamageEvent.cs
Source/ACE.Server/Managers/QuestManager.cs
Source/ACE.Server/WorldObjects/Creature_Combat.cs
Source/ACE.Server/WorldObjects/Creature_Magic.cs
Source/ACE.Server/WorldObjects/Creature_Rating.cs
Source/ACE.Server/WorldObjects/Creature_Tick.cs
Source/ACE.Server/WorldObjects/Gem.cs
Source/ACE.Server/WorldObjects/Monster_Awareness.cs
Source/ACE.Server/WorldObjects/Player.cs
Source/ACE.Server/WorldObjects/Player_Ability.cs
Source/ACE.Server/WorldObjects/Player_Character.cs
Source/ACE.Server/WorldObjects/Player_Combat.cs
Source/ACE.Server/WorldObjects/Player_Melee.cs
Source/ACE.Server/WorldObjects/Player_Missile.cs
Source/ACE.Server/WorldObjects/SpellProjectile.cs
Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
Source/ACE.Server/WorldObjects/WorldObject_Use.cs
Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
Source/ACE.Server/starterGear.json

- Updates upgraded Combat Focuses and grants each of them an activated ability (see Server Changes for details)
- DB PR will include Mana Barrier and Activate Combat Ability gems

Update combat abilities

---

Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs

- makes all loot gen bows wood material type for immersion and to ensure sufficient woodcrafting materials

update-wooden bows

---

Source/ACE.Entity/Enum/WeenieType.cs
Source/ACE.Server/Factories/WorldObjectFactory.cs
Source/ACE.Server/WorldObjects/Player_Inventory.cs
Source/ACE.Server/WorldObjects/RetainingChisel.cs
Source/ACE.Server/starterGear.json

- creates a reusable tool to retain/unretain items at no cost
- added one + Ust to starter gear

feat: retaining chisel

---

Source/ACE.Server/WorldObjects/Player_Inventory.cs
Source/ACE.Server/WorldObjects/WorldObject_Properties.cs

- now properly deattunes only those items with Ivoryable set to true

fix: automatic ivorying

---

Source/ACE.Server/Managers/PropertyManager.cs
Source/ACE.Server/WorldObjects/Monster_Awareness.cs

- reduces custom visual range setting

fix-visual range

---

Source/ACE.Server/WorldObjects/Player_Inventory.cs

* prevent non-buckler shields from being equippable with thrown weapons.
* prevent bucklers from being equippable with thrown weapons unless skill is specialized.

feat: thrown weapons spec bonus

---

Source/ACE.Server/Entity/DamageEvent.cs

Reduce bonuses from 20% to 15%.

feat: adjust attack height bonuses for spec skills

---

Source/ACE.Entity/Enum/Properties/PropertyInt.cs
Source/ACE.Entity/Enum/SpellId.cs
Source/ACE.Server/WorldObjects/Container.cs
Source/ACE.Server/WorldObjects/WorldObject_Properties.cs

This reverts commit 35bea0456b31b8d6c734d7d5d58870727ed55240.

Revert "feat: allow vendors to sell items with shared cooldowns (#121)"

---

Source/ACE.Entity/Enum/CombatAbility.cs
Source/ACE.Entity/Enum/Properties/PropertyInt.cs
Source/ACE.Entity/Enum/WeenieType.cs
Source/ACE.Server/Entity/Confirmation.cs
Source/ACE.Server/Entity/DamageEvent.cs
Source/ACE.Server/Factories/WorldObjectFactory.cs
Source/ACE.Server/WorldObjects/CombatFocus.cs
Source/ACE.Server/WorldObjects/CombatFocusAlterationGem.cs
Source/ACE.Server/WorldObjects/Gem.cs
Source/ACE.Server/WorldObjects/Player_Ability.cs
Source/ACE.Server/WorldObjects/Player_Combat.cs
Source/ACE.Server/WorldObjects/Player_Melee.cs
Source/ACE.Server/WorldObjects/Player_Spells.cs
Source/ACE.Server/WorldObjects/WorldObject_Properties.cs

* Rebalance spells lists.
* New Item: Alteration Gems, sold at the Combat Focus Trainer. Allows players to swap 1 attribute spell and 1 skill spell on a Combat Focus for another of each.
* Rename Reckless ability to Fury.

feat: update combat focus system

---

Source/ACE.DatLoader/DatManager.cs

feat: create 5 duplicates of each capstone dungeon

---

Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs

- adds 25% chance on proc spell to reduce mana cost by half
- chance and reduction bonus scaled for skill

feat: lore spec bonus

---

Source/ACE.DatLoader/DatManager.cs
Source/ACE.Server/Factories/PlayerFactory.cs

Restore classic training academies

---

Source/ACE.DatLoader/DatManager.cs

* Remove Falatacot stuff in desert near Yaraq.
* Remove Marae Lassel portal base near Rithwic.
* Remove snowman near Le-Ai Rea.
* Ensure "NoobFence" code is correctly positioned.

feat: cell.dat (30003) updates

---

Source/ACE.Server/WorldObjects/Player_Missile.cs

- fixes updateammo use after launch

fix: ammo use

---

Source/ACE.Server/Entity/DamageEvent.cs
Source/ACE.Server/WorldObjects/Creature_Combat.cs

* Increase shield's effective angle to 225 degrees when specialized (from 180).
* (this is in addition to the doubled effective shield skill spec bonus)

feat: additional shield spec bonus

---

Source/ACE.Server/WorldObjects/SpellProjectile.cs

When monster tries to "defend a spell critical strike" using perception.

fix: null reference error

---

Source/ACE.Server/Factories/LootGenerationFactory_Jewelry.cs

Commented out in case we want to use them at some point.

feat: disable special jewelry rolls

---

Source/ACE.Server/WorldObjects/SpellProjectile.cs

- updates volley stamps scaling factor for overload and jewelcrafting ramping effects to account for strikethrough

update: volley stamps

---

Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs
Source/ACE.Server/Factories/LootGenerationFactory_Weapon.cs
Source/ACE.Server/Factories/LootTables.cs

feat: apply implicit bonuses to thrown weapons

---

Source/ACE.Server/WorldObjects/Creature_Missile.cs

fix: allow thrown projectiles to inherit damage value

---

Source/ACE.Server/WorldObjects/Jewel.cs
Source/ACE.Server/WorldObjects/Salvage.cs

- updates salvage class to differentiate between missile and missilelaunchers in validation
- fixes unsocketing for loop

update: tinkering/jewelcrafting support for thrown

---

Source/ACE.Server/Factories/LootGenerationFactory.cs
Source/ACE.Server/Factories/Tables/GemMaterialChance.cs

* all materials for gems have equal chance of occurring.
* fixed jewelry not having material.

feat: adjust gem chances

---

Source/ACE.DatLoader/DatManager.cs

* Change "Augmented Understanding" spell names to:
* Rested
* Well Rested
* Very Well Rested
* Requires portal.dat (30016)

feat: change spell name (new portal.dat)

---

Source/ACE.DatLoader/DatManager.cs

feat: remove casino buildings (new cell.dat)

---

Source/ACE.DatLoader/DatManager.cs

- Icons should load properly with dat-patching from base EoR
- Requires portal.dat (30017)

feat: fixed icons portal.dat dat-patching

---

Source/ACE.Server/WorldObjects/SpellProjectile.cs
Source/ACE.Server/WorldObjects/WorldObject_Magic.cs

- reduces overload bonus to +25% max, to put it in line with Fury

fix: overload scaling

---

Source/ACE.Server/WorldObjects/CombatFocus.cs
Source/ACE.Server/WorldObjects/Gem.cs
Source/ACE.Server/WorldObjects/Player_Ability.cs
Source/ACE.Server/WorldObjects/SpellProjectile.cs
Source/ACE.Server/WorldObjects/WorldObject_Magic.cs

- adds effects for focii activations , mana barrier and shrouding

Update particle effects for activated combat abilities

---

Source/ACE.Server/Factories/Tables/VendorBaseItems.cs
Source/ACE.Server/WorldObjects/Vendor.cs

- updates vendor base items to include new special packs

update: add special packs to vendors

---

Source/ACE.DatLoader/DatManager.cs

* new icons for combat abilities

feat: portal.dat (30018)

---

Source/ACE.Server/WorldObjects/Player_Ability.cs

- adds a vanish - stamina cost and thievery vs. perception check for monsters within 10 meters of the player, with a generous bonus to skill since failure on one monster here means vanish has no effect at all.   monsters at a distance are more easily fooled by the smoke bomb and don't need a check? :P
- just changed the wording on phalanx broadcast, since additional requirements checks in this part of the code place the activated ability on cooldown with no effect, which seems unnecessarily punishing, and inserting checks earlier would be clumsy.

update: vanish activated requirements

---

Source/ACE.DatLoader/DatManager.cs

* fix uneven terrain near Olthoi North (Gaerlan's Citadel)

feat: cell.dat (30005)

---

Source/ACE.Server/WorldObjects/Player_Inventory.cs

* prevent re-calculation when creating a character

fix: bandaid for RecalculateBurden null reference

---

Source/ACE.DatLoader/DatManager.cs

* portal.dat (30019) - new icons
* cell.dat (30006) - fixed various terrain (burnt ground, unaligned terrain, craters)

feat: update dats

---

Source/ACE.Entity/Enum/ItemType.cs
Source/ACE.Server/Factories/Tables/VendorBaseItems.cs
Source/ACE.Server/WorldObjects/Vendor.cs

* Add base items for archmage and bowyer
* Add new option that allows listed items to only appear in a certain tier

feat: update archmage/bowyer base items

---

.gitignore
Source/ACE.Server/ACE.Server.csproj
Source/ACE.Server/Discord/DiscordBot.cs
Source/ACE.Server/Discord/InteractionHandler.cs
Source/ACE.Server/Program.cs
Source/ACE.Server/appsettings.json

Add channel update timers for Population and Time of Day

feat: add discord bot

---

Source/ACE.Server/WorldObjects/Player_Combat.cs

- prevents negative fury display to players

fix: negative fury

---

Source/ACE.Server/WorldObjects/Jewel.cs

-missing method call for calculating jewel quality

fix: malachite

---

Source/ACE.Server/WorldObjects/Jewel_Bonuses.cs

- fix formula for self-harm damage

fix: hematite

---

Source/ACE.Server/WorldObjects/Jewel.cs

- ensures correct display and wield location for socketed rings/bracelets

fix: ring wield error

---

Source/ACE.Server/WorldObjects/Creature_Death.cs

- mana barrier now dispels on death

fix: mana barrier dispel on death

---

Source/ACE.Server/WorldObjects/WorldObject_Magic.cs

- fixes wrong reference in amethyst jewel bonus check which was causing harms to do 0 damage

fix: nullification

---

Source/ACE.Server/WorldObjects/Salvage.cs

* Adjust tinkering requirements so that one tink costs units of savage equal to 'target workmanship' x 'target slots'. (previously 10 x slots)
* Adjust xp formula so that more xp is awarded at lower skill level and higher difficulty tinks award up to double xp.
* Allow failed tinks to some grant xp.
* Delete bags of salvage that have 0 structure after a tink.
* Tweak some wording for confirmations and result strings.

feat: tweak tinkering formulas

---

Source/ACE.Server/WorldObjects/Player_Crafting.cs

- creates a new method of sending salvage messages in order to include new skill names
- includes Jewelcrafting and Woodworking in the list of possible creature skills to select from when picking the one to use for salvage operations
- possibly not the most important thing since atm skill does not grant any bonus, so could just use this same new message function and remove the skill part entirely (or add a skill bonus at some point, maybe as a spec thing)

fix: new skill names in salvaging message

---

Source/ACE.Server/WorldObjects/Salvage.cs

* Also reduce xp awarded for low-end tinks from 100% to 50% per slot.

fix: adjust difficulty check to not use absolute value

---

Source/ACE.Server/WorldObjects/Salvage.cs

- had elementaldamagebonus check not elementaldamagemod, so GG wasn't working.
- made other parts of the code a bit more readable in the process

fix: wand salvage not working

---

Source/ACE.Server/WorldObjects/ArmorPatch.cs

- adds a check to ensure patches can't be applied to undergarments

update: armor patch

---

Source/ACE.Server/Physics/PhysicsObj.cs

- volleys should now collide with non-creature weenie objects and will not pass through

fix: volleys through objects

---

Source/ACE.Server/WorldObjects/Player_Ability.cs

- adds handling for death on overload self-harm

update: overload self-kill

---

Source/ACE.Server/WorldObjects/Jewel_Bonuses.cs

- doubles base ramp stamps for jewel properties
- adds player broadcasts for vitals restoring jewel properties
- ensures clean death for bloodstone self-harm deaths

update: jewel proc messages and stamp increases

---

Source/ACE.Server/WorldObjects/Jewel_Bonuses.cs

- fixes to ensure shield+weapon applicable jewels can work on shield

fix: shield and weapon jewel fix

---

Source/ACE.Server/Entity/DamageEvent.cs

- needed to set evasionMod for the damage calculation formula

fix: furious blow and steady shot evasion

---

Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs

- removes outdated code that clears off wield reqs on non-magical cloth armor

fix: cloth dropping without wield req

---

Source/ACE.Server/WorldObjects/Vendor.cs

- fix typo in colier and add lost wish mountains for surnad/denterra

update: vendor towns

---

Source/ACE.Server/WorldObjects/Creature.cs
Source/ACE.Server/WorldObjects/Monster_Awareness.cs
Source/ACE.Server/WorldObjects/Monster_Combat.cs
Source/ACE.Server/WorldObjects/Player_Ability.cs
Source/ACE.Server/WorldObjects/Player_Combat.cs

- Fix errors and adjust mechanics.
- Increase range of Threatening Shout from 5 to 10.
- Increase range of Feign Weakness from 5 to 15.

feat: update threat system

---

Source/ACE.Server/WorldObjects/WorldObject_Use.cs

- mistakenly removed cooldown start on activated abiltiies, changed to just prevent on mana barrier

fix: cooldown on activated abilities

---

Source/ACE.Server/Discord/Modules/AccountModule.cs

extract methods to make list-players cleaner

fix: remove table from list-players when filtering admins and no one else is online

---

Source/ACE.Entity/Enum/PartialEvasion.cs
Source/ACE.Server/Entity/DamageEvent.cs
Source/ACE.Server/WorldObjects/Player_Combat.cs
Source/ACE.Server/WorldObjects/SpellProjectile.cs
Source/ACE.Server/WorldObjects/WorldObject_Magic.cs

* Removed minor and major partial evades. Now just a singular partial evade. ("glancing blow" and "partial resist")
* A partial evade reduces damage by 50%.
* On a successful defense skill check, there is a:
* 25% chance to full evade.
* 50% chance to partial evade.
* 25% chance for no evade.

feat: partial evasion rework

---

Source/ACE.Server/Factories/LootGenerationFactory.cs
Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs
Source/ACE.Server/Factories/LootTables.cs
Source/ACE.Server/Factories/Tables/VendorBaseItems.cs
Source/ACE.Server/Network/Structure/AppraiseInfo.cs
Source/ACE.Server/WorldObjects/ManaStone.cs
Source/ACE.Server/WorldObjects/SpellTransference.cs

* Quest gear mutation system updates.
* Base stats are the floor of the tier. Each stat can mutate towards the ceiling of the tier.
* Max mana and mana rates adjusted for quest items and lootgen.
* Mana stones/charges rebalanced.
* Archmage vendor stock of mana stones/charges updated.

feat: Mutable quest item overhaul

---

Source/ACE.Server/Managers/PropertyManager.cs
Source/ACE.Server/WorldObjects/Container.cs
Source/ACE.Server/WorldObjects/Player_Inventory.cs
Source/ACE.Server/WorldObjects/Storage.cs
Source/ACE.Server/WorldObjects/WorldObject_Database.cs

- Allow bank to save correctly when splitting and/or merging stacks to and from the main bank pack.
- Bank storage saves correctly when equipping an item directly from the bank.
- Added a toggleable server property: "debug_banking_system".

feat: update banking system

---

Source/ACE.Server/Network/Structure/AppraiseInfo.cs
Source/ACE.Server/WorldObjects/Player_Inventory.cs

* Side-pack to side-pack saving.
* Moving containers around within the bank.

fix: various bank fixes

---

Source/ACE.Server/WorldObjects/Container.cs
Source/ACE.Server/WorldObjects/Creature_Equipment.cs
Source/ACE.Server/WorldObjects/Player_Inventory.cs

remove encumbrance burden recalculation when player removes item from inventory 
misc formatting

fix: send encumbrance value when player equips item

---

Source/ACE.Entity/Enum/EmoteType.cs
Source/ACE.Entity/Enum/SpellCategory.cs
Source/ACE.Entity/Enum/SpellId.cs
Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs

- add emote that can remove enchantments
- add potion spell categories
- update PhysScript to be able to optionally target the player using an object

feat: support olthoi potions

---

apps/server/WorldObjects/Player_Awareness.cs
apps/server/WorldObjects/Player_Combat.cs
apps/server/WorldObjects/Player_Death.cs
apps/server/WorldObjects/Player_Spells.cs

apply and remove new combat run debuff when entering and exiting combat mode respectively
apply and remove new stealth run debuff when entering and exiting stealth respectively

fix(server): remove run exploit by swapping weapons while in combat mode

---

apps/server/WorldObjects/Managers/EmoteManager.cs
libs/entity/Enum/EmoteType.cs

- new emote that allows all fellows to get quest stamped when one player does.

feat: add StampQuestForAllFellows emote

---

apps/server/Entity/Landblock.cs
apps/server/Managers/PropertyManager.cs

- Add new Long Property for adjusting minimum_spawn_density in realtime.
- Reduce default minimum_spawn_density (from 12 to 8)
- Refactor minimum_spawn_density into its own method.

feat: adjust minimum_spawn_density

---

apps/server/Managers/PropertyManager.cs
apps/server/WorldObjects/Container_Properties.cs
apps/server/WorldObjects/Logging/BankLogContainer.cs
apps/server/WorldObjects/Logging/BankLogItem.cs
apps/server/WorldObjects/Logging/BankLogPlayer.cs
apps/server/WorldObjects/Player_Inventory.cs
apps/server/WorldObjects/Player_Inventory_Banking.cs
apps/server/WorldObjects/Storage.cs
apps/server/WorldObjects/WorldObject_Database.cs
libs/entity/Enum/Properties/PropertyBool.cs

- Add detailed transaction logging for every transaction scenario.
- Refactor transaction code into its own methods.
- Remove redundant code for some transactions.
- Prevent Bank Golems from appearing on Radar and Nearby Item Selection hotkeys.

feat: improve banking functionality

---

apps/server/Factories/LootGenerationFactory.cs

-  add null check and error message.

feat: check for null when mutating quest weapons

---

apps/server/WorldObjects/Managers/EmoteManager.cs

- Refactor into new methods.
- Remove dungeon tier as part of calculations. Instead, player level contributes towards getting better items.
- Overhaul calculations for which rewards are received and how many of them.

feat: overhaul capstone reward emote

---

apps/server/Factories/Tables/SpellLevelProgression.cs
libs/entity/Enum/SpellId.cs

- to support upgrading the Baron's Amulet.

feat: add new life give spell tiers

---

apps/server/Command/Handlers/PlayerCommands.cs

- Allow players to invite other players to their fellow from anywhere, using '/invite <player name>'.

feat: Invite fellow command

---

apps/server/WorldObjects/Monster_Awareness.cs

- Convert unnecessary public properties to private/protected.
- Fix potential system null errors.
- Move special rating checks into their own function.
- Various other minor code reformats.

refactor: Monster_Awareness

---

apps/server/Entity/DamageEvent.cs
apps/server/WorldObjects/Hotspot.cs
apps/server/WorldObjects/Jewel_Bonuses.cs
apps/server/WorldObjects/SpellProjectile.cs

- Convert unnecessary public properties to private.
- Move all special rating checks into their own functions.
- Add summaries for each special rating method.
- Various other code reformats.

refactor: jewel_bonuses class

---

apps/server/Physics/PhysicsObj.cs
apps/server/WorldObjects/SpellProjectile.cs

- Convert unnecessary public properties to private.
- Move all SpecialRating/CombatAbility/SpecBonus checks into their own functions.
- Add summaries for each.
- Various other code reformats.

refactor: spell_projectile class

---

apps/server/Entity/DamageEvent.cs
apps/server/WorldObjects/SpellProjectile.cs

to Elemental Ward, Physical Ward, and Bravado.

feat: add rating summary details

---

apps/server/WorldObjects/Player_Melee.cs
apps/server/WorldObjects/Player_Missile.cs

- Partial refactor or Player_Missile class.
- Move Slash Rating check into its own function.
- Add detailed summary.
- Convert unnecessary public properties to private.
- Fix potential system null errors.

refactor: player_missile class

---

apps/server/WorldObjects/Food.cs
apps/server/WorldObjects/Gem.cs
apps/server/WorldObjects/Player_Magic.cs
apps/server/WorldObjects/WorldObject_Magic.cs

- Convert unnecessary public properties to private/protected.
- Fix many potential system null errors.
- Move Special Rating (jewel), Spec Bonus, and Combat Ability code checks into their own functions.
- Add descriptive summaries for each.
- Various other minor code reformats.

refactor: WorldObject_Magic class

---

apps/server/Entity/Spell.cs
apps/server/WorldObjects/Creature_Equipment.cs
apps/server/WorldObjects/Jewel.cs
apps/server/WorldObjects/Jewel_Bonuses.cs
apps/server/WorldObjects/Player_Tick.cs
apps/server/WorldObjects/WorldObject_Properties.cs
libs/entity/Enum/Properties/PropertyInt.cs

- Refactor rating code into own functions.
- Fix "useage" typos.

refactor: comp burn and item mana usage

---

apps/server/WorldObjects/Hotspot.cs

- from 1% per rating to 0.5% per rating

feat: reduce rating hotspot chance

---

apps/server/WorldObjects/UpgradeKit.cs

- Will need to expand if ratings get added to the mutable quest stat system.

feat: add special ratings to quest gear upgrade kit

---

apps/server/WorldObjects/UpgradeKit.cs

- Upgrading to wield req:
- 125: 1 kit
- 175: 2 kits
- 200: 3 kits
- 215: 4 kits
- 230: 5 kits
- 250: 6 kits
- 270: 7 kits

feat: require more upgrade kits for higher tier upgrades

---

apps/server/Command/Handlers/PlayerCommands.cs
apps/server/Entity/AllegianceNode.cs
apps/server/Managers/AllegianceManager.cs
apps/server/WorldObjects/Player_Allegiance.cs
apps/server/WorldObjects/Player_Xp.cs

- fix calculation issues.
- add player command '/allegiance-rank' to provide information on how the current character's rank is determined.

feat: enhance allegiance code

---

apps/server/WorldObjects/Jewel.cs
apps/server/WorldObjects/Salvage.cs

- Don't consume source salvage when tinkering.
- Prevent jewel carving from setting jewel quality to 1 from have 0 skill.

feat: improve bypass crafting checks setting

---

apps/server/Entity/DamageEvent.cs

- Never evade.
- Never block.
- All hits received are critical.

feat: increase peace mode combat penalties

---

apps/server/Factories/LootGenerationFactory_Clothing.cs

Base armor/ward stats:
- Robes/ClothArmor: 75 armor, 7 ward
- Amuli/Chiran: 80 armor, 6 ward
- Leather/Yoroi/Lorica: 80 armor, 5 ward
- Studded/Koujia: 85 armor, 5 ward
- Chain/Scale/Nariyid: 90 armor, 5 ward
- Plate/Celdon: 95 armor, 5 ward
- Cov/Olthoi: 100 armor, 5 ward

feat: rebalance AL/Ward values on different armor styles

---

apps/server/Entity/LevelScaling.cs

Will result in increased damage dealt to players.

feat: adjust armor, ward, and health values for level scaling

---

apps/server/WorldObjects/Creature_ArchetypeSystem.cs

feat: change health archetype to not consider "physicality"

---

apps/server/Factories/LootGenerationFactory_Clothing.cs

- Cloth: 7 -> 10
- Amuli/Chiran: 6 -> 9
- Everything else: 5 -> 7

feat: increase base ward levels on lootgen slightly

---

apps/server/Factories/PlayerFactory.cs
apps/server/WorldObjects/Managers/EmoteManager.cs

- Remove previous method of checking all other account characters for every InqQuest check. This was performance heavy and caused delayed reactions in-game.
- When stamping a player's quest that starts with "ACCOUNT_", also stamp the quest on every other character of the same account.
- When creating a new character, search all other characters on the account for account quest stamps and add them to the new character.

feat: improve account quest stamping system

---

apps/server/Entity/DamageEvent.cs
apps/server/WorldObjects/Gem.cs
apps/server/WorldObjects/Player.cs
apps/server/WorldObjects/Player_Character.cs
apps/server/WorldObjects/Player_Combat.cs
apps/server/WorldObjects/SpellProjectile.cs
libs/entity/Enum/CharacterOption.cs
libs/entity/Enum/CombatAbility.cs

- Works just like Mana Barrier but based on stamina instead of mana, and Run/Jump skills instead of Mana Conversion.
- Cannot be used at the same time as Mana Barrier and shares a cooldown.

feat: add new Evasive Stance skill

---

apps/server/Entity/DamageEvent.cs

fix: prevent damage events with "placeholder" weenie

---

apps/server/Factories/LootGenerationFactory.cs

- Also fix sigil trinket categories.

fix: set correct tier reference for mutable quest gear

---

apps/server/Factories/LootGenerationFactory.cs

feat: update quest armor level mutation formula

---

apps/server/Entity/DamageEvent.cs
apps/server/WorldObjects/Creature_Properties.cs
apps/server/WorldObjects/Creature_Vitals.cs

- Also refactor some of the armor mod code.

feat: enable percent-based vital regen for monsters

---

apps/server/WorldObjects/Player_Xp.cs

- Also fix combat focus level up check.

feat: add account quest stamps certain player levels during beta

---

apps/server/Entity/SigilTrinketEvent.cs
apps/server/Factories/LootGenerationFactory_SigilTrinket.cs

- From +25% damage to +50% critical damage.

feat: change Assailment puzzle box buff to critical damage

---

apps/server/WorldObjects/WorldObject_Magic.cs

- Also change Reflect Foci and Familiarity bonuses to be additive instead of multiplicative.

fix: resist chance mod issue

---

apps/server/Entity/Spell.cs

- Make sure magic skill mods are considered when calculating the skill mod bonus for burn rates.

feat: update component burn rate

---

apps/server/Entity/SigilTrinketEvent.cs
apps/server/Factories/LootGenerationFactory_SigilTrinket.cs

- Clarify description.
- Increase amount absorbed from 25% to 50%.

feat: update absorption top description and amount absorbed

---

apps/server/WorldObjects/SpellTransference.cs

fix: spell transference cost

---

apps/server/WorldObjects/Managers/EmoteManager.cs

- To track down Capstone boss kill stamp issues.

feat: add logging to StampQuestForAllFellows emote

---

apps/server/WorldObjects/Salvage.cs

- BaseDifficulty = ItemWork x 20 - 20. (0 to 180)
- WorkmanshipMod = SalvageWork - ItemWork x 20. (-180 to 180)
- AttemptsMod = AttemptNum x 0.1 + 1. (1.1 to 2.0)
- **FinalDifficulty = BaseDifficulty x WorkmanshipMod x AttemptsMod. (0 to 720)**

feat: adjust tinkering difficulty formula

---

apps/server/WorldObjects/Container.cs

Using GameMessageUpdateObject().

feat: update quest objects when mutated

---

apps/server/WorldObjects/Player_Inventory.cs
apps/server/WorldObjects/Player_Networking.cs
apps/server/WorldObjects/Salvage.cs

- also audit inventory for leftover empty bags on login.

fix: consume salvage correctly when it has 0 uses left

---

apps/server/WorldObjects/WorldObject_Use.cs

- From 5 seconds to 10 seconds.

feat: extend time to use expose weakness and taunt

---

apps/server/WorldObjects/Managers/EmoteManager.cs
apps/server/WorldObjects/Player_Inventory.cs

- NPCs only take specific GUIDs for items with trophy quality.

fix: ensure emotes that take multiple items succeed

---

apps/server/Factories/LootTables.cs

feat: add TW mutation damage ranges

---

apps/server/WorldObjects/Creature_Combat.cs

- Increase the base animation speed mod from 0.8 to 1.0.

feat: update base animation speed mod

---

apps/server/WorldObjects/Monster_Navigation.cs

fix: prevent movetohome error

---

apps/server/WorldObjects/Jewel_Bonuses.cs

- Change amount received to 10% of damage instead of 100%.

fix: vital on-hit jewels

---

apps/server/WorldObjects/Creature_BodyPart.cs
apps/server/WorldObjects/Managers/EnchantmentManager.cs
apps/server/WorldObjects/Managers/EnchantmentManagerWithCaching.cs
apps/server/WorldObjects/SpellProjectile.cs
apps/server/WorldObjects/WorldObject_Magic.cs
libs/entity/Enum/EnchantmentTypeFlags.cs

-  Also change Expose Weakness spells to be multiplicative instead of flat amounts.
- Debuffs per spell level: 21%, 22%, 23%, 24%, 25%, 26%, 27%.

fix: add ward enchantment mod logic

---

apps/server/WorldObjects/Player_Location.cs

To help with players occasionally getting stuck there.

feat: set LB 0x0000 to no log

---

apps/server/WorldObjects/Player_Tick.cs

From 10% per tick to 5% per tick.

feat: lower adrenaline/charge reduction tick amount

---

apps/server/Entity/DamageEvent.cs
apps/server/WorldObjects/Gem.cs
apps/server/WorldObjects/Player_Ability.cs
apps/server/WorldObjects/Player_Combat.cs
libs/entity/Enum/CombatAbility.cs

- Condense all Enchanted Blade abilities into one ability.
- Use attack height and a weapon's proc spell school to determine which spell fires.

feat: update enchanted blade

---

apps/server/starterGear.json

- remove taunt, stealth, mana barrier.
- increase pyreals from 300 to 500.

feat: update starter gear

---

apps/server/WorldObjects/Healer.cs
apps/server/WorldObjects/Managers/EnchantmentManager.cs
libs/entity/Enum/Properties/PropertyInt.cs

Will need edits once new spells are created.

feat: prepare stamina/mana HoTs for new kits

---

apps/server/WorldObjects/Player_Ability.cs

Some logic is placed to allow for advanced spells to be cast once we implement a way to upgrade the abilities.

feat: update enchanted blade to initially only cast bolts and heal self

---

apps/server/WorldObjects/Creature_ArchetypeSystem.cs

- T0: none
- T1: 75 > 50
- T2: 200 > 150
- T3: 300 > 225
- T4: 400 > 300
- T5: 500 > 400
- T6: 600 > 500
- T7: 700 > 600

feat: lower enemy defenses

---

apps/server/WorldObjects/Healer.cs

feat: update healkit cooldown length

---

apps/server/Entity/Landblock.cs
apps/server/WorldObjects/Storage.cs

fix: prevent bank biota save duplication

---

apps/server/WorldObjects/Healer.cs
apps/server/WorldObjects/Player_Combat.cs
libs/entity/Enum/SpellId.cs

-  Also reduce effectiveness that healkit mod has on the HoT effect by 50%.

feat: revert healing kit cooldowns to being shared

---

apps/server/WorldObjects/Creature_Combat.cs
apps/server/WorldObjects/SkillFormula.cs

Removed extra    )   in BiotaPropertiesEnchantmentRegistry 

---

apps/server/Entity/Landblock.cs
apps/server/WorldObjects/Creature_ArchetypeSystem.cs

Only works for Lugian Mines and Mines of Despair atm.

feat: allow dungeon mods to transfer to part 2 dungeons
