daralet-ac/ACE

Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs
Cloth
- Robes have Armor Level instead of Impen.
- Aegis for Amuli/Chiran increased from 5 -> 7
Light
- Lorica Armor Level reduced from 85 -> 75. Resource pen removed.
- StuddedL/Koujia/OlthoiKoujia Armor Level increased from 85 -> 90.
Heavy
- Chain/Scale Armor Level increased from 90 -> 100. -Nariyid resource pen reduced from 5% -> 3%.
- Plate/Celdon/OlthoiCeldon Armor Level set from 100 -> 110. Resource pen reduced from 5% -> 4%.
- Covenant/Olthoi Aegis Level increased from 0 -> 5. Resource pen reduced from 6% -> 5%.
=> feat: rebalance armor classes

Source/ACE.Server/WorldObjects/SkillAlterationDevice.cs
Add "removed" skills to skip list (missile def, dirty fighting, recklessness)
=> fix: skill alteration device error

Source/ACE.Server/WorldObjects/Creature_Combat.cs
- For players, this is handled through the expose weakness abilities now.
- Also lower chance for a monster to attempt this every 10 seconds, from 50% to 10%
=> feat: remove player logic from perceive weakness function

Source/ACE.Server/Entity/StaminaTable.cs, Source/ACE.Server/WorldObjects/Creature_Vitals.cs, Source/ACE.Server/WorldObjects/Player_Combat.cs, Source/ACE.Server/WorldObjects/Player_Melee.cs, Source/ACE.Server/WorldObjects/Player_Missile.cs
- Incorporate weapon animation base length into the cost formula, scaling down costs with faster weapons.
- Increase the base stamina cost of an attack from '20 per tier' -> '20 per tier + 20'.
- Reduce diminishing return of vital regeneration (increasing regen rates slightly).
- Reduce cost of dual wield attacks if Dual Wield is specialized.
=> feat: update attack stamina costs

Source/ACE.Server/Entity/StaminaTable.cs, Source/ACE.Server/Managers/PropertyManager.cs, Source/ACE.Server/Physics/Animation/MotionTable.cs, Source/ACE.Server/WorldObjects/Player_Combat.cs, Source/ACE.Server/WorldObjects/Player_Melee.cs, Source/ACE.Server/WorldObjects/Player_Missile.cs
-Stamina cost formula includes the final 'attacks per second' of an attack. Faster weapons cost proportionally less stamina. This also scales with all gains to weapons speed, including quickness and swift killer buffs. Attacking with faster weapons faster will never lead to more stamina use overtime.
-Reverted missile animation shenanigans back to retail state.
=> feat: balance stamina costs, missile animation changes

Source/ACE.Server/Entity/DamageEvent.cs, Source/ACE.Server/Factories/LootGenerationFactory_Caster.cs, Source/ACE.Server/Factories/LootGenerationFactory_Chance.cs, Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs, Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs, Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs, Source/ACE.Server/Factories/LootGenerationFactory_Spells.cs, Source/ACE.Server/Factories/LootGenerationFactory_Weapon.cs, Source/ACE.Server/Network/Structure/AppraiseInfo.cs
* Weapons now use base attributes and trained weapon skill for wield reqs.
* **Martial Weapons:** Strength and trained Martial Weapons.
* **Thrown Weapons:** Strength and trained Thrown Weapons.
* **Bows:** Coordination and trained Bows.
* **Dagger:** Coordination and trained Daggers. 
* **Staff:** Coordination and trained Staff.
* **Unarmed:** Coordination and trained Unarmed Combat.
* **War Magic:** Self and trained War Magic.
* **Life Magic:** Self and trained Life Magic.
* Armor now only uses one attribute type for it's wield req.
* **Heavy:** Strength.
* **Light:** Coordination.
* **Cloth:** Self.
=> feat: update wield reqs

Source/ACE.Server/WorldObjects/Monster_Magic.cs
- adds a bit of logic to monster spellcasting to weight the likelihood of casting any with values set to 2.0
- most likely will be used with drain/heal self but could increase risk by adding more dangerous damage spells this way
- todo: increase healing effectiveness on monsters to account for their higher base health
=> feat: simple ai health recovery

Source/ACE.DatLoader/DatManager.cs, Source/ACE.Server/Entity/DamageEvent.cs, Source/ACE.Server/Factories/LootGenerationFactory_Caster.cs, Source/ACE.Server/Factories/LootGenerationFactory_Chance.cs, Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs, Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs, Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs, Source/ACE.Server/Factories/LootGenerationFactory_Weapon.cs, Source/ACE.Server/Factories/LootTables.cs, Source/ACE.Server/Factories/Tables/Wcids/Weapons/CasterWcids.cs, Source/ACE.Server/Network/Structure/AppraiseInfo.cs, Source/ACE.Server/WorldObjects/Creature_Combat.cs, Source/ACE.Server/WorldObjects/Creature_Vitals.cs, Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs, Source/ACE.Server/WorldObjects/SpellProjectile.cs, Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
* feat: update spell damage calculations
- Spell damage scales of primary attribute instead of magic skill.
- Spell crit damage works like other weapons now (max spell damage x2).
- Bonus magic defense implicit mod moved from Orb to Staff. (Staff has magic and physical d bonuses)
- Orb now has Aegis Cleaving implicit.
- Weapon mod rolls adjusted (attack skill and defenses).
- Casters can now roll with +magic skill mod (equivalent to +attack skill mods).
- Removed "Life" casters. All casters roll with an element AND restoration bonus mod, but Life req casters have higher resto bonus and War req caster have higher elemental damage bonus.
- Adjusted appraise info ordering of item mods.
- Mana regens as fast as Stamina (10% per 5 seconds, Health is still 5%).
- Fixed elemental damage mod …
=> Spell damage balancing

Source/ACE.Entity/Enum/Properties/PropertyFloat.cs, Source/ACE.Server/Entity/DamageEvent.cs, Source/ACE.Server/Factories/LootGenerationFactory_Caster.cs, Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs, Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs, Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs, Source/ACE.Server/Factories/LootGenerationFactory_Weapon.cs, Source/ACE.Server/Network/Structure/AppraiseInfo.cs, Source/ACE.Server/WorldObjects/Player_Combat.cs, Source/ACE.Server/WorldObjects/Player_Melee.cs, Source/ACE.Server/WorldObjects/Player_Missile.cs, Source/ACE.Server/WorldObjects/SpellProjectile.cs, Source/ACE.Server/WorldObjects/WorldObject_Properties.cs, Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
- Halve all current weapon spec bonuses (and add War spec bonuses)
- Axe/Dagger/Bow/Scepter: +5% crit chance
- Mace/Staff/Atlatl/Wand: +50% crit damage
- Spear/Crossbow/Orb: +10% ignore armor/aegis
- Sword/UA: +10% Stamina Cost Reduction
- Add implicit bonuses to weapons that match the spec bonus
- Axe/Dagger/Bow/Scepter: +0-10% crit chance
- Mace/Staff/Atlatl/Wand: +0-100% crit damage
- Spear/Crossbow/Orb: +0-20% ignore armor/aegis
- Sword/UA: +0-20% Stamina Cost Reduction
- Staff (caster): +0-10% defense mods
- New stat: Stamina Cost Reduction
- Add implicit bonuses to workmanship calculation
- (Damage x2 + Mods + Implicit) / 4
- Adjust Aegis/Armor Cleaving text on appraisal
=> feat: add implicit bonuses to weapons that match their spec bonuses

Source/ACE.Entity/Enum/EmoteType.cs, Source/ACE.Server/WorldObjects/Creature_Properties.cs, Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- allows monsters to set some of their own properties
- spells can only change a handful of things and the decreased duration of debuffs/buffs limits that further
=> feat: monster stat setting emotes

Source/ACE.Entity/Enum/WeenieType.cs, Source/ACE.Server/Managers/RecipeManager.cs
- adds a not-wielded requirement to recipemanager by default (yes I know about blockWielded) to prevent issues with equipped item ratings with jewel unsocketing and tinkering/untinkering.
- also resorted WeenieTypes so existing weenies have the proper numbers
=> fix-recipe wield check

Source/ACE.Server/WorldObjects/Player_Inventory.cs, Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- attuned but ivoryable items now immediately become unattuned + wielder linked on pickup
- restricting quest item use to one player only was the goal of attunement, and ivory was a workaround to allow players to mule said quest items. But it is an unnecessary extra step
=> feat: automatic ivorying

Source/ACE.Server/WorldObjects/Player_Magic.cs, Source/ACE.Server/WorldObjects/Player_Skills.cs
* portal magic spells never fizzle.
* prevent using unassigned xp to raise portal magic.
=> feat: adjust portal magic rules

Source/ACE.Entity/Enum/EmoteType.cs, Source/ACE.Server/Entity/Proficiency.cs, Source/ACE.Server/Managers/RecipeManager.cs, Source/ACE.Server/Network/GameAction/Actions/GameActionRaiseSkill.cs, Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs, Source/ACE.Server/WorldObjects/Player_Skills.cs
- provides support for simple ranking up of portal magic and trade skills without fiddling around with granting xp that doesn't count towards total etc.
- crafting leveling now handled with a chance to rank up on recipe use, rather than granting proficiency xp
- essentially these skills will function as though experience didn't exist--cannot spend xp into them, or gain any through any means, and of course get none back on untraining
=> feat: award skill ranks

Source/ACE.Server/WorldObjects/Player_Skills.cs, Source/ACE.Server/WorldObjects/SkillAlterationDevice.cs
- adds a separate code path to deal with trade skill untraining that refunds no credits (preivous check in player skills did not work)
- handles TradeSkill limiting quest stamps (the issue with just using an emote on the forgetfulness gem is that it fires off at the start of the code sequence regardless of whether you confirm to untrain the skill, so you could get your quest stamps removed and get multiple skills, and a purely weenie based approach did not seem to work with a contained gem (though it does with a remote-used object)
=> update- trade skill untraining

Source/ACE.Entity/Enum/EmoteType.cs, Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs
- adds an emote to grant capstone cache rewards
- bonus chance for extra rewards above a certain tier
- has limited base pool of rewards it picks from but can expand that based on cache type, tier, etc.
- pass in quest name in message and amount of rewards
=> feat: capstone cache reward emote

Source/ACE.Entity/Enum/Properties/PropertyInt.cs, Source/ACE.Entity/Enum/SpellId.cs, Source/ACE.Server/WorldObjects/Container.cs, Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
* Items must use a different Int to set a shared cooldown on the sql file (Int 456 - VendorItemSharedCooldown).
* SharedCooldown gets copied over after an item is purchased.
=> feat: allow vendors to sell items with shared cooldowns

Source/ACE.Server/WorldObjects/CombatFocus.cs, Source/ACE.Server/WorldObjects/CombatFocusAlterationGem.cs
- Adds wielded check to prevent removed spells from remaining applied
- moves validation checks from add/remove spell, placing them before confirmation
- adds reset option (no SpellId on Gem) which destroys old focus and gives you a new copy
- adds skill/attribute add/remove to dialog box
=> update: focus alteration gems

Source/ACE.Server/WorldObjects/Hotspot.cs
- ensures hotspots only hit monsters when either AffectsAis or AffectsOnlyAis is set to true.
=> fix: hotspots

Source/ACE.Server/WorldObjects/Creature_Combat.cs
- adds up to 50% chance to sneak from the front with spec deception
- chance and damage bonus scale, depending on ratio of deception skill to attack skill
=> feat- decept spec bonus

Source/ACE.Server/Factories/LootGenerationFactory_Caster.cs
* Give caster staves an additional bonus amount to defense mods based on weapon tier.
* The other subtypes bonuses already have tier scaling. This one was missed.
=> feat: enhance staff caster bonus mods

Source/ACE.Server/WorldObjects/Door.cs
- removes the ability to open locked doors from behind (I assume this was retail behavior that was maintained for the sake of fidelity, but it just encourages cheese).
=> fix: locked doors

Source/ACE.DatLoader/DatManager.cs, Source/ACE.Entity/Enum/EmoteType.cs, Source/ACE.Entity/Enum/Properties/PropertyBool.cs, Source/ACE.Entity/Enum/Properties/PropertyString.cs, Source/ACE.Server/Command/Handlers/AdminCommands.cs, Source/ACE.Server/Entity/Fellowship.cs, Source/ACE.Server/Entity/GeneratorProfile.cs, Source/ACE.Server/Entity/Landblock.cs, Source/ACE.Server/Managers/WorldManager.cs, Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs, Source/ACE.Server/WorldObjects/Player.cs, Source/ACE.Server/WorldObjects/Player_Location.cs, Source/ACE.Server/WorldObjects/WorldObject_Magic.cs, Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
-adds capstone instancing, details follow.
- also includes support to enable relative generation to work on any landblock with no changes to the weenies
Players and Fellowships now have a CapstoneDungeon property, which is a uint copy of a landblock Id.
Landblocks now have:
- CapstoneMax - max number of players on a capstone landblock
- CapstonePlayers - a dictionary of Player / double (for timers). By default the timer is set to 0, but timer starts when player leaves a dungeon or are added to the list when a fellow member enters the dungeon.
- CapstoneSeatHolder - 10 minutes (in seconds), serving as a timer for above
- CapstoneLockout - On LB heartbeat, it checks for any object with DungeonLockout bool and if so, lb sets this to true.  If true, no new players can be added to the …
=> update: capstone landblock selection

Source/ACE.Server/Entity/DamageEvent.cs, Source/ACE.Server/WorldObjects/SpellProjectile.cs
- adds 50% chance to avoid a critical strike with perception spec, scaling with skill
- also removes unnecessary usings from damage event
=> feat: perception spec bonus

Source/ACE.Server/WorldObjects/WorldObject_Magic.cs, Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- adds heatseeking blast code
- if spelltype isn't blast, we just create projectiles as usual, otherwise we create a list of targets near our main target, filter them for 2 additional valid ones, then create projectiles for those + main target.
- damage is scaled by 75% if 2 targets, by 2/3 if 3 targets.
=> feat: heatseeking blasts

Source/ACE.Server/WorldObjects/Player.cs
* Cast a buff spell on self when jumping.
* Does not improve the first jump. Player must do a brief jump to gain the buff first.
* Current spell is a placeholder (RareJump). Will eventually be a custom spell that doubles skill.
* This is in addition to the half-fall damage bonus that is already implemented.
=> feat: jump spec bonus

Source/ACE.Server/WorldObjects/Lock.cs
* Up to 50% chance to increase lootquality by 25%, when picking a chest with a lockpick.
* (this is in addition to the stealth bonuses for thievery)
=> feat: thievery spec bonus

Source/ACE.Entity/Enum/Properties/PropertyBool.cs, Source/ACE.Server/WorldObjects/Monster_Tick.cs, Source/ACE.Server/WorldObjects/Player_Awareness.cs, Source/ACE.Server/WorldObjects/Player_Monster.cs, Source/ACE.Server/WorldObjects/WorldObject.cs
* Add bool for special creatures that shouldn't be able to break player stealth (watchers, etc).
* Adjust detection rules:
* Monster can gain up to x2 Perception skill depending on how close the player is to them.
* Monster can gain up to x2 Perception skill depending on what side of the monster the player is standing (x2 directly in front, x0 directly behind)
* Each monster can only attempt to detect a nearby stealth player once every 3 seconds. (previously they were making 10+ attempts per second)
=> feat: improve stealth detection system

Source/ACE.Server/Factories/LootGenerationFactory.cs, Source/ACE.Server/Factories/LootTables.cs
* Greatly simplified and no longer references the db.
* Less random material combinations. More logical now.
* Only some gemtypes added (to Orb drops). Imbue gems only available from actual gems atm.
TODO
* Need to add WCIDs for metal thrown weapons.
* Make Koujia chest/leggings use metal instead of leather.
* Possibly add more gemtypes.
* Check for other specific loot types that need adjusting.
=> feat: adjust lootgen material system

Source/ACE.Server/Physics/PhysicsObj.cs, Source/ACE.Server/WorldObjects/SpellProjectile.cs, Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
On hitting a target with a volley projectile:
1. Check to ensure target's guid is not on the StrikethroughTargets list
2. Call the ProjectileImpact method if the projectile has struck three targets
3. Increment the projectile's Strikethrough
4. Add the target's guid to the StrikethroughTargets list 
5. During damage calculation, scale down damage based on previous targets hit
During collision detection: 
1. Allow strikethrough projectiles (volleys only atm) to transition cleanly through a target, as though it were ethereal
2. Prevent collisions from stopping the projectile until it reaches 3 targets (Double checked to ensure no projectiles are persisting on the landblock)
=> feat: strikethrough volleys

Source/ACE.Server/WorldObjects/Player_Awareness.cs
- just adds a translucency 1/visibility check since all watchdogs that we wouldn't want breaking stealth are one of those
=> update: watcher stealth detection

Source/ACE.Entity/Enum/Properties/PropertyBool.cs, Source/ACE.Server/WorldObjects/Hotspot.cs, Source/ACE.Server/WorldObjects/Player.cs, Source/ACE.Server/WorldObjects/Player_Networking.cs, Source/ACE.Server/WorldObjects/WorldObject.cs
* Hotspot created by a campfire requires CampfireHotspot bool to be set to true to work.
* Once player receives the "Gazing into the fire calms your soul." message, it will not appear again until after player stands up.
* Campfire buff effect no longer applies until the player stands up.
* Placeholder buff changed to Augmented Understanding I.
* Future:
* Make 3 tiers of campfires for 3 different levels of buff effects?
* Create different types of campfire with different spells? Or allow manipulating of campfires by cooking different foods in them to change the active spell?
=> feat: update campfire mechanics

Source/ACE.Database/SerializedShardDatabase.cs, Source/ACE.Database/ShardDatabase.cs, Source/ACE.Entity/Enum/Properties/PropertyInstanceId.cs, Source/ACE.Server/Command/Handlers/AdminCommands.cs, Source/ACE.Server/WorldObjects/Container.cs, Source/ACE.Server/WorldObjects/Jewel.cs, Source/ACE.Server/WorldObjects/Player_Inventory.cs, Source/ACE.Server/WorldObjects/Salvage.cs, Source/ACE.Server/WorldObjects/Storage.cs, Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- repurposes Storage to create player banking system
- when players use a banking golem, query the DB for items flagged with the AccountId (as BankAccountID on the item)
-  add them to the golem's inventory (while removing from their original containers/inventories)
- show them to the player in a storage window.
- any bank golem in the world will show the same items to any character on the players account
- removing and adding items to the bank does not play the pickup animation, so players can move their items in and out quickly and efficiently 
- when players place items into this window, they are stamped with the BankAccountID
- when players withdraw items, BankAccountID is set to 0
- includes checks / DB saves for players moving items within storage window to ensure position placement …
=> Feat banking

Source/ACE.Entity/Enum/Properties/PropertyFloat.cs, Source/ACE.Entity/Enum/Properties/PropertyInstanceId.cs, Source/ACE.Entity/Enum/Properties/PropertyString.cs, Source/ACE.Server/Entity/AllegianceNode.cs, Source/ACE.Server/Entity/Fellowship.cs, Source/ACE.Server/Entity/IPlayer.cs, Source/ACE.Server/Entity/Landblock.cs, Source/ACE.Server/Entity/OfflinePlayer.cs, Source/ACE.Server/Managers/AllegianceManager.cs, Source/ACE.Server/Physics/Common/Landblock.cs, Source/ACE.Server/WorldObjects/Player_Allegiance.cs, Source/ACE.Server/WorldObjects/Player_Skills.cs, Source/ACE.Server/WorldObjects/Player_Xp.cs, Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
On swearing:
- If no loyalty skill, train it.
- if Patron no leader skill, train it
- vassal stamped with UnixTime they swore - SworeAllegiance
- vassal stamps themselves with AllegianceLog = Patron Name, Acct Id, Time of swearing (currently unused but I expect it could be valuable)
- if player had a previous patron, reduce loyalty by half. No penalty if the vassal is just reswearing to one of their previous patron's other characters (accountID check)
Earning Loyalty:
- Players earn experience into Loyalty at a base rate of 1 rank of skill per 1 player level general XP gained
- This rate increases over time the player is sworn to patron, up to an additional 1 rank of skill / level after 3 months
- This rate increases by an additional 1 rank / level while player is in a fellow with their …
=> feat: allegiance rework

Source/ACE.Entity/Enum/Properties/PropertyBool.cs, Source/ACE.Entity/Enum/Properties/PropertyFloat.cs, Source/ACE.Server/Factories/LootGenerationFactory.cs, Source/ACE.Server/Network/Structure/AppraiseInfo.cs, Source/ACE.Server/WorldObjects/Container.cs, Source/ACE.Server/WorldObjects/Creature_Equipment.cs, Source/ACE.Server/WorldObjects/Creature_Properties.cs, Source/ACE.Server/WorldObjects/WorldObject.cs, Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
* Item must have MutableQuestItem bool set to true.
* As item enters player inventory, it mutates.
* Item receives up to a 20% increase to its stats.
* There are greatly diminished chances to receives a higher bonus %.
* 5% or more = 50% chance
* 10% or more = 30% chance
* 15% or more = 13% chance
* 19% or more = 1% chance
* Stats that can be mutated
* Damage, DamageMod, ElementalDamageMod, ElementalDamageBonus, AttackMod, PhysicalDefenseMod, MagicDefenseMod, RestorationMod, Armor, Aegis, ArmorProtectionLevels, ArmorSkillMods, WeaponSkillMods.
=> feat: add mutable quest item system

Source/ACE.Entity/Enum/CombatAbility.cs, Source/ACE.Server/Entity/DamageEvent.cs, Source/ACE.Server/Entity/Fellowship.cs, Source/ACE.Server/Factories/PlayerFactory.cs, Source/ACE.Server/WorldObjects/Creature_Combat.cs, Source/ACE.Server/WorldObjects/Gem.cs, Source/ACE.Server/WorldObjects/Player_Location.cs, Source/ACE.Server/WorldObjects/Player_Spells.cs, Source/ACE.Server/WorldObjects/Portal.cs, Source/ACE.Server/WorldObjects/SpellProjectile.cs, Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
- players with the scaling debuff will have their damage done and received scaled when fighting monsters below them in level, including flat 15% penalties to evasion and resistance (both incoming and outgoing)
- scaler debuff enables players to bypass MaxLevel restrictions on portals, so they can enter capstones only if scaled.
- recalculates fellow xp share split based on whether a player is scaled or not, allowed scaled players up to 25 levels above lowest in fellow to join as if they were same level
- scaler cannot be deactivated in fellowship or while inside a dungeon to prevent cheating
- also removed restrictions on Lifestone Recall and eliminates marketplace recall
=> feat: level scaling

Source/ACE.Server/Managers/WorldManager.cs, Source/ACE.Server/WorldObjects/Container.cs, Source/ACE.Server/WorldObjects/Player_Inventory.cs
- enables the creation of item packs which only contain certain item types, by setting the MerchandiseItemType on the pack weenie
- items in the pack only contribute half their weight toward burden (player burden must be recalculated when inventory changes to ensure this works)
=> feat: special item packs

Source/ACE.Server/WorldObjects/Container.cs, Source/ACE.Server/WorldObjects/Player_Inventory.cs
- moves automatic ivorying to TryAddtoInventory to ensure it applies to craft, pickup, and emote give items
=> fix: automatic ivorying

Source/ACE.Entity/Enum/Properties/PropertyBool.cs, Source/ACE.Server/Entity/DamageHistory.cs, Source/ACE.Server/Entity/DamageHistoryInfo.cs, Source/ACE.Server/WorldObjects/Creature_Combat.cs, Source/ACE.Server/WorldObjects/Creature_Death.cs
- adds prototype low-tier endgame system whereby shrouded(scaled) players have a chance to gain a piece of alt currency upon killing lower tier monster (increased if accompanied by appropriate-tier lowbie)
- can be expanded to trigger spawns, events, etc.
- when a creature is struck by a player 10+ levels above them who doesn't have the shroud debuff, they will stamp themselves StruckByUnshrouded.
- upon death, if a creature does not have StruckByUnshrouded (ie. no unscaled high level players have helped kill), they will check their DamageHistory to see if any scaled 10+ level players did 1/3 or more of total damage.
- if so, they assign a flat chance and then check to see if any appropriate level players (5 levels on either side of monster level) did 1/3 damage or more of the damage too, …
=> feat: low-tier endgame

Source/ACE.Server/WorldObjects/Creature_Death.cs
- damage threshold for scaled player contribution now 10%
- bonus chance for accompanying lowbies now only applies if total lowbie damage is 50% or greater
- basechance for each scaled player scales depending on the proportion of damage they've done, non-linearly up to 50% max
=> update: low tier endgame

Source/ACE.Entity/Enum/EmoteType.cs, Source/ACE.Server/Managers/RecipeManager.cs, Source/ACE.Server/WorldObjects/Jewel.cs, Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs, Source/ACE.Server/WorldObjects/Player_Skills.cs, Source/ACE.Server/WorldObjects/Salvage.cs
- replaces pure chance + full rank gain approach with 20% of a ranks worth of xp directly into skill for feeling of progression, as with leadership/loyalty
- adds AwardNoContribSkillXP emote to support campfire/alchemy table xp granting
=> update: crafting xp gain

Source/ACE.Server/WorldObjects/Monster_Awareness.cs, Source/ACE.Server/WorldObjects/Monster_Magic.cs, Source/ACE.Server/WorldObjects/Monster_Melee.cs, Source/ACE.Server/WorldObjects/Monster_Missile.cs, Source/ACE.Server/WorldObjects/Player_Ability.cs, Source/ACE.Server/WorldObjects/Player_Awareness.cs
- adds Vanish combat ability, requires Trained Thievery (decept too? or spec?) 
- -Immediately enter stealth, with no failure chance 
-Monsters attacking that player will check on next attack initialization and will be forced to find a new target, and remove player from their targets lists 
-Creatures on trying to detect stealth will fail for the next 5 seconds, but afterwards stealth can be broken normally
- also adds a combat mode check before dispelling mire foot on EndStealth();
=> feat: vanish

Source/ACE.Server/Factories/Tables/Wcids/ArmorWcids.cs
- reworks armor drop chances, ensuring each category drops head, hand and footwear at a similar rate
- other single slot armor types with multislot overlap have their drop chances reduced somewhat, and multislot does as well(should be rarer now, not hauberks for days)
=> update: armor chances

Source/ACE.Server/WorldObjects/Creature.cs
- fixes wonky missile/magic cleaves
- distance sorted result from BuildTargetDistance was not being captured previously so it was just using the unsorted list
=> fix: wonky cleaves

Source/ACE.Server/Factories/Tables/VendorBaseItems.cs, Source/ACE.Server/WorldObjects/Vendor.cs
* Add remaining color palettes for new special packs.
* Add Heritage option to vendor tables
* Reorganize pack offerings for Shopkeepers by heritage/color and add more offerings.
* Add "Apprentice" template type to vendor table.
=> feat: update vendor base items

Source/ACE.Server/Factories/LootGenerationFactory_Caster.cs, Source/ACE.Server/WorldObjects/Monster_Awareness.cs, Source/ACE.Server/starterGear.json
* prevent monster from aggroing a player it just killed (max aggro range of 50 when searching for new targets)
* fix starter comps wcids
=> fix: monster aggro and starter comps

Source/ACE.Server/Entity/Proficiency.cs
* to prevent: occasional stealth success checks award huge amounts of xp.
=> fix: prevent stealth success chances from awarding xp

Source/ACE.Server/WorldObjects/Creature_ArchetypeSystem.cs, Source/ACE.Server/WorldObjects/Creature_Death.cs, Source/ACE.Server/WorldObjects/Player_Xp.cs
* Starter tier changes (1-10):
* Health reduced from 10-100 to 10-50
* Expected % damage per attack reduced from 1.5-2.0 to 1.0-1.5
* Experience earned per kill increased from 1% to 5%.
* Experience gained per kill "limit" increased from 5% to 10%.
=> feat: update starter tier monsters

Source/ACE.Server/WorldObjects/Player_Magic.cs
- players were getting "You can't spend xp in portal magic" messages when casting spells
=> fix: no proficiency xp for portal magic

Source/ACE.Server/Managers/RecipeManager.cs
- players without jewelcrafting can carve jewels, but will get null value when attempting to grant xp.
- needs rethinking but this is bandaid for null crash
=> fix: untrained jewelcrafting crash

Source/ACE.Entity/Enum/Properties/PropertyDataId.cs, Source/ACE.Server/WorldObjects/SpellTransference.cs, Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
- confirmation runs a method a second time after the player hits "yes" so it was rolling for a new spell each time, and players were extracting the wrong spells from multi-spell items
- adds a check to roll for a new spell from the selected item ONLY if unconfirmed, and saves that spellID onto the pearl itself to preserve the player's choice
=> fix: multi-spell transfer selection

Source/ACE.Server/WorldObjects/Entity/CreatureAttribute.cs, Source/ACE.Server/WorldObjects/Player_Inventory.cs
- on equip/deequip now adds/removes gear rating amount to the appropriate player attribute's StartingValue
- previously the benefit was only being registered in the appraisal window--now the character attribute and skills panel will properly reflect the bonuses
- StartingValue is used in Base calculation so code here no longer needed
=> fix: attribute jewels

Source/ACE.Server/WorldObjects/Gem.cs, Source/ACE.Server/WorldObjects/WorldObject_Use.cs
- removes busy check on combat ability use, allowing them to be used instantaneously regardless of whether player is in the middle of an animation
=> update: remove busy check from combat ability use

Source/ACE.Server/WorldObjects/SpellProjectile.cs
- adds player reference to EnchantmentManager for cooldown on mana barrier after being broken by a spell projectile
=> fix: missing mana barrier destruction reference

Source/ACE.Entity/Enum/ItemType.cs, Source/ACE.Server/WorldObjects/Vendor.cs
* When a vendor NPC is loaded, update its MerchandiseItemTypes value based on its Template string.
* Also fixes vendors not accepting trade notes and other items.
=> feat: control vendor merchandise item types with templates

Source/ACE.Server/WorldObjects/Player_Ability.cs, Source/ACE.Server/WorldObjects/Player_Melee.cs
- doubles base rate of building fury
- reduces stamina cost to a max of 50% extra
- reduces self-harm chance to a max of 7.5% from 10%
=> update: fury stamps and stam cost

Source/ACE.Server/WorldObjects/Creature_Magic.cs, Source/ACE.Server/WorldObjects/Player_Ability.cs
- doubles base rate players build overload
- reduces max mana cost increase to 50%
- self-harm chance reduced to 7.5%
=> update: overload stamps, mana cost, self harm chance

Source/ACE.Server/WorldObjects/Creature_Magic.cs, Source/ACE.Server/WorldObjects/Player_Ability.cs, Source/ACE.Server/WorldObjects/SpellProjectile.cs, Source/ACE.Server/WorldObjects/WorldObject_Magic.cs, Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
- fix overload activated effectiveness bonus to properly grant only double
- adds a modified message to alert players that a spell was impacted by the overload activated ability
=> update: overload fixes

Source/ACE.Server/Entity/DamageEvent.cs, Source/ACE.Server/WorldObjects/Player_Ability.cs, Source/ACE.Server/WorldObjects/Player_Combat.cs
- made reckless activated proc unevadable to match overload
- fury self-damage now a flat 50% of damage done to foe (or max 10% of player health) to prevent armor mitigation
- updates attack message to indicate the activated proc
- ensures clean death if player dies due to self-harm
- fix random chance to float, was proccing 50% because of ints
=> update: fury fixes

Source/ACE.Server/WorldObjects/Player_Combat.cs, Source/ACE.Server/WorldObjects/SpellProjectile.cs
- eliminates chance for health damage to fire off twice on certain hits (likely the cause of double deaths if the first hit kills player?)
=> Fix mana barrier double kill

Source/ACE.Server/WorldObjects/Player_Ability.cs
- adds missing fs to ensure random float not int
=> fix: overload self-harm chance

Source/ACE.Server/Factories/LootGenerationFactory_Caster.cs, Source/ACE.Server/Factories/LootGenerationFactory_Clothing.cs, Source/ACE.Server/Factories/LootGenerationFactory_Dinnerware.cs, Source/ACE.Server/Factories/LootGenerationFactory_Jewelry.cs, Source/ACE.Server/Factories/LootGenerationFactory_Magic.cs, Source/ACE.Server/Factories/LootGenerationFactory_Melee.cs, Source/ACE.Server/Factories/LootGenerationFactory_Missile.cs, Source/ACE.Server/Factories/LootGenerationFactory_Spells.cs
* Allow CoS spells to roll on items that don't have other spells.
* Set chance for any melee/missile weapon to have a CoS spell to 25%.
* Reduce base Arcane Lore requirements for magic gear by 25 points in each tier.
* Refactor AssignMagic code.
=> feat: cast-on-strike rebalance

Source/ACE.Server/Entity/Landblock.cs
- fix ensures we check to see if any of the fellow members are already a part of this capstone landblock's player list before adding them, since trying to add them a second time caused a crash
=> fix: capstone dictionary crash

Source/ACE.Server/WorldObjects/SpellTransference.cs
- now properly takes target Tier before the long-description--previously was just using the base pearl's tier
=> fix: spell transfer pearl

Source/ACE.Server/Entity/GeneratorProfile.cs, Source/ACE.Server/Entity/Landblock.cs, Source/ACE.Server/WorldObjects/WorldObject_Generators.cs
- encounter generators are now given a 180s cooldown interval, which is only triggered after a monster they generated is killed, ensuring at least 3 mins passes before the gen can respawn again, regardless of the RegenerationInterval
- monster camp creatures are grandchildren of the encounter and wouldn't trigger this,  but shouldn't need to since atm camp gens don't regen at all basically, and the generator holds the slot?
=> update: encounter cooldown

Source/ACE.Server/Managers/AllegianceManager.cs, Source/ACE.Server/WorldObjects/Player_Allegiance.cs, Source/ACE.Server/WorldObjects/Player_Xp.cs
* Rebalance passup xp
* Change vassal generated xp range from 0% to 50% to 5% to 10%, depending on vassal Loyalty.
* Change patron received xp range from 0% to 100% to 25% to 100%, depending on patron Leadership and Rank.
* Final xp gained range for patrons: 1% to 10%.
* Adjust Leadership skill leveling
* Formula = CachedXp * FellowshipMod * TimeSwornMod
* Adjust Loyalty skill leveling
* Add a levelOffset mod to prevent slower loyalty leveling rate at high player levels.
* Formula = ProportionCurrentLevelXpEarned * LevelOffset * LoyaltyRankXpCost * FellowshipMod * TimeSwornMod
=> Passup xp adjustments

Source/ACE.Server/Managers/PropertyManager.cs, Source/ACE.Server/WorldObjects/Monster_Awareness.cs, Source/ACE.Server/WorldObjects/WorldObject_Magic.cs
* Adjust minimum threat level to be the same as starting threat level (100).
* Reduce support spell threat range (from caster) to 3 from 20.
* Reduce support spell threat gained amount to (2 x spell level) from (5 x spell level).
* Make sure self-target spells don't add threat.
* Add server property (debug_threat_system) that can be turned on for detailed threat console logging for all active players.
=> feat: adjust threat system

Source/ACE.Server/Managers/PropertyManager.cs, Source/ACE.Server/Managers/RecipeManager.cs, Source/ACE.Server/WorldObjects/Jewel.cs, Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs, Source/ACE.Server/WorldObjects/Player_Crafting.cs, Source/ACE.Server/WorldObjects/Salvage.cs
- Update crafting xp rewards for Tinkering, Jewelcrafting, Cooking, and Alchemy.
- Successful crafts award an amount of xp depending on the following:
- Cost of current skill rank.
- Overall skill level progress, from 1 to 200 skill. (mod scales from 50% to 1%)
- Relative difficulty of craft attempt, from -50 (easy) to 50 (hard). (mod scales from 50% to 200%)
- Relative difficulty must be higher than -50 to receive any xp.
- FinalXp = RankCost * ProgressMod * DifficultyMod.
- Campfire and Alchemy Table emote scripts updated to work with this system.
=> Crafting xp tweaks

Source/ACE.Server/WorldObjects/SpellProjectile.cs
- eliminates cooldown for anything but being broken by monster damage
=> fix: bandaid for strikethrough null refernece

Source/ACE.Server/WorldObjects/Creature_Death.cs, Source/ACE.Server/WorldObjects/Player_Combat.cs, Source/ACE.Server/WorldObjects/SpellProjectile.cs, Source/ACE.Server/WorldObjects/WorldObject_Use.cs
- removes mana barrier cooldown on death and on manual untoggling--only way mana barrier goes on cooldown now is if it is broken by zeroing out on mana
- adds IsInDeathProcess checks before OnDeath/Die is called, and sets it as true if the check is passed (as opposed to base ACE where it is not set to true until Die is called).  Hopefully, this will prevent these methods from being called twice in a row before player receives lifestone protection, whatever the cause
=> fix: mana barrier/double kills

Source/ACE.Server/Managers/WorldManager.cs
- replaces a straight method call to recalc burden with a 3 sec delayed action chain, to hopefully ensure it fires off on the live server so players login with the proper burden
=> fix: burden on login

Source/ACE.Server/Entity/BaseDamageMod.cs, Source/ACE.Server/Network/Structure/WeaponProfile.cs, Source/ACE.Server/WorldObjects/Player.cs
* Remove spell cast text. (still displays spell expire text)
* Prevent variance buff from occurring.
* This is a bandaid fix that disables variance buffs altogether. The VarianceMod float id is 22, same as the Jump skill id. Even when using the Skill enchantment flag, instead of the float flag, it still seems to cause both the jump buff and variance buff to occur simultaneously. We don't use variance buffs atm so it is currently not a problem to disable it. Would have to revisit this issue if we ever want to use variance buffs.
=> feat: adjust jump spec issues

Source/ACE.Server/Network/Structure/AppraiseInfo.cs, Source/ACE.Server/WorldObjects/Creature_Combat.cs, Source/ACE.Server/WorldObjects/Monster_Melee.cs
- Armor mod bonuses to shield skill correctly increase shield AL.
- Shield skill level is correctly "effectively" doubled when specialized.
- Refactor some shield and armor AL calculations.
=> fix: allow shield skill to manipulate shield AL properly

Source/ACE.Server/Factories/LootGenerationFactory.cs, Source/ACE.Server/Factories/Tables/Wcids/EmpoweredScarabWcids.cs
* blue = lv 20+ enemies
* yellow = lv 50+ enemies
* red = lv 75+ enemies
=> feat: set empowered scarab drop tiers

Source/ACE.Server/Factories/LootGenerationFactory.cs, Source/ACE.Server/Managers/PropertyManager.cs
* Increase the potency of a creatures' "in-tier level" effect on loot quality for lower tiers.
* Creatures towards the end of their respective tiers drop greatly increased loot quality and a chance for an additional item.
* This effect diminishes in potency at higher tiers.
=> feat: update loot quality scaling per tier

Source/ACE.Server/Entity/DamageEvent.cs, Source/ACE.Server/Entity/LevelScaling.cs, Source/ACE.Server/Managers/PropertyManager.cs, Source/ACE.Server/WorldObjects/Creature.cs, Source/ACE.Server/WorldObjects/Creature_BodyPart.cs, Source/ACE.Server/WorldObjects/Creature_Combat.cs, Source/ACE.Server/WorldObjects/Creature_Death.cs, Source/ACE.Server/WorldObjects/Creature_Properties.cs, Source/ACE.Server/WorldObjects/Monster_Melee.cs, Source/ACE.Server/WorldObjects/Player_Combat.cs, Source/ACE.Server/WorldObjects/Player_Melee.cs, Source/ACE.Server/WorldObjects/Player_Missile.cs, Source/ACE.Server/WorldObjects/SpellProjectile.cs, Source/ACE.Server/WorldObjects/WorldObject_Magic.cs, Source/ACE.Server/WorldObjects/WorldObject_Weapon.cs
Rework shroud level scaling.
* Refactored into a new class to minimize code in other classes.
* Accurately calculates various stats for scaling, for any character up to level 125 to scale down to any level (min level 10).
* Health, attack skill, defense skill, attributes, armor, ward, resistance, and life spells.
* Utilizes attribute scaling to scale attack speed and attribute mod for players.
* Utilizes attack skill scaling to scale hit/resist chance and imbue effectiveness for players.
* Utilizes defense skill scaling to scale evade chance and defense skill spec bonus effects for players.
* Utilizes health, armor, ward, and resistance scaling to decrease damage dealt to monsters and increase damage dealt to players.
* Utilizes life spell boost scaling to scale harm, drain, and …
=> Shroud level scaling rework

Source/ACE.Entity/Enum/Properties/PropertyBool.cs, Source/ACE.Server/WorldObjects/EmpoweredScarab.cs, Source/ACE.Server/WorldObjects/Hotspot.cs, Source/ACE.Server/WorldObjects/Player_EmpoweredScarab.cs, Source/ACE.Server/WorldObjects/WorldObject.cs
- If player has carrying an empowered scarab and standing on the hotspot, a particle effect will flash every 3 seconds.
- While empowered scarab recharge is occurring, the flashing will occur more frequently.
=> feat: make menhir hotspot easier to identify

Source/ACE.Server/Physics/PhysicsObj.cs
Spell projectiles now correctly collide with game objects like doors. Only creature item types can be passed through.
=> fix: prevent spells from avoiding collision

Source/ACE.Server/WorldObjects/Vendor.cs
- Vendors now also look for nearby NPCs to set the tier of their wares.
- Allows for use of generic vendors (peddlers, archmages, etc) that are near other static NPCs as long as the static NPC has its Tier int (10007) set.
=> feat: improve vendor tier scanning

Source/ACE.Entity/Enum/EmoteType.cs, Source/ACE.Entity/Enum/Properties/PropertyInt.cs, Source/ACE.Entity/Enum/SpellCategory.cs, Source/ACE.Entity/Enum/SpellId.cs, Source/ACE.Entity/Models/PropertiesEnchantmentRegistry.cs, Source/ACE.Server/Entity/AddEnchantmentResult.cs, Source/ACE.Server/Entity/DamageHistoryInfo.cs, Source/ACE.Server/Factories/Tables/StackableSpellTables.cs, Source/ACE.Server/Network/Structure/Enchantment.cs, Source/ACE.Server/WorldObjects/Creature_Death.cs, Source/ACE.Server/WorldObjects/Creature_Equipment.cs, Source/ACE.Server/WorldObjects/Managers/EmoteManager.cs, Source/ACE.Server/WorldObjects/Managers/EnchantmentManager.cs, Source/ACE.Server/WorldObjects/Player_Death.cs, Source/ACE.Server/WorldObjects/Player_Spells.cs, Source/ACE.Server/WorldObjects/Player_Xp.cs, Source/ACE.Server/WorldObjects/WorldObject_Properties.cs
Adds a system that allows players to increase the difficulty of a region for themselves, while also providing better rewards.
- Allow certain buffs/debuffs to stack their effects when applied on top of each other.
- Stacks of spells are tracked in the spell registry.
- Stackable debuff spells last 1 hour and persist through death.
- Monster 'Create Tables' can now be affected by a killer's current debuff stacks.
- Implemented for Olthoi North enemies.
- Using acid dropped by each worker/soldier/lancer/noble applies a unique stackable debuff.
- The more debuffs a player has, the higher chances that each item in an olthoi's create table will drop.
- Also increases xp gained from killing olthoi and chances to spawn special olthoi.
=> feat: spell stacking system (difficulty pushing)

apps/server/WorldObjects/Creature_Death.cs
- When killing enemies that can have drop bonuses due to player debuff stacks, use average debuff stacks of all players in the fellowship who contributed to the kill.
=> Spell stack bonus for fellowships

apps/server/WorldObjects/Monster_PlayerScaling.cs, apps/server/WorldObjects/Monster_Tick.cs, apps/server/WorldObjects/WorldObject.cs, apps/server/WorldObjects/WorldObject_Properties.cs, libs/entity/Enum/Properties/PropertyBool.cs, libs/entity/Enum/Properties/PropertyFloat.cs, libs/entity/Enum/Properties/PropertyInt.cs
- Optional settings for monsters to dynamically scale their stats if multiple players are nearby. Can set:
- Threshold for how many players must be nearby before scaling starts.
- How much vitals/attack/defense will be scaled per extra player nearby.
- TODO: Allow additional monsters to spawn when scaling a monster.
- Occurs on monster generation and continues to check for new nearby players on every monster tick.
- Monsters can only scale upward, when more players appear nearby (not downward when players disappear).
=> Player count scaling

apps/server/Managers/PropertyManager.cs, apps/server/WorldObjects/Creature_Death.cs, apps/server/WorldObjects/Player_Spells.cs, apps/server/WorldObjects/Player_Xp.cs, apps/server/WorldObjects/WorldObject_Properties.cs, libs/entity/Enum/Properties/PropertyBool.cs
- Allow monsters to have a ShroudedKillXpReward bool set. If true, shrouded players earn xp as if the monster was the level of the player.
- Caps at current soft level cap of 50.
- Refactor some of the Xp calculation code.
- Move overlevelPenalty mod into XpType.Kill block.
- Move altBonus and regionalDebuffBonus mods to after monster kill xp cap calculations. This also allows them to apply to quest xp gains.
=> feat: add appropriate xp rewards for shrouded players

apps/server/WorldObjects/Creature_ArchetypeSystem.cs
- Physical and Magic Defense skills no longer use the Toughness archetype in their formulas.
- This allows us to pump up the Toughness stat to boost an enemy's health without boosting their defenses.
=> feat: adjust archetype formulas

apps/server/WorldObjects/Creature_ArchetypeSystem.cs
- Physical Defense is now only based on Dexterity.
- previously Physicality and Dexterity.
- Armor is now only based on Physicality.
- previously Toughness and Physicality.
- Ward is now only based on Magic.
- previously Toughness and Magic.
=> feat: update archetype formulas

apps/server/WorldObjects/Managers/EmoteManager.cs
- revert to allowing each capstone to set 'amount' of rewards.
- awarded trade notes amount equal to double the set reward amount.
- TODO: create dungeon modifier system that can make dungeons harder and increase the reward amount.
=> feat: update capstone reward system

apps/server/Entity/LevelScaling.cs
- also add error logging for when a monster doesn't have a level set.
=> fix: check monster.Level for null during level scaling

apps/server/Entity/Confirmation.cs, apps/server/Factories/LootGenerationFactory.cs, apps/server/Factories/LootGenerationFactory_Jewelry.cs, apps/server/Factories/LootTables.cs, apps/server/Factories/WorldObjectFactory.cs, apps/server/WorldObjects/Container.cs, apps/server/WorldObjects/Managers/EmoteManager.cs, apps/server/WorldObjects/UpgradeKit.cs, apps/server/WorldObjects/WorldObject.cs, libs/entity/Enum/ArmorStyle.cs, libs/entity/Enum/Properties/PropertyBool.cs, libs/entity/Enum/WeenieType.cs
- A new item that can be earned through completing capstone dungeons.
- Can be used on quest gear items that have the 'UpgradeableQuestItem' flag. (mostly capstone quest gear)
- If the player can wield a higher tier version of the quest item, it will be upgraded to the highest possible tier the player can wield.
- All stats on the item scale up to the new tier, retaining the "roll qualities" that the item mutated to when the player picked it up initially.
- Includes damage, damage mod, elemental damage mod, resto mod, armor level, ward level, attack/defense mods, skill mods, ratings, and spells.
- Also sets the correct total mana and mana rate for the new tier.
- TODO: Scale spellcraft.
- Add and refactor some code in the Loottable class.
=> feat: upgrade kits

apps/server/WorldObjects/Gem.cs
- add extra conditional checks to prevent being able to disable shroud during a portal recall into a capstone dungeon.
- while performing any "busy" actions.
- while teleporting.
- for 5 seconds after any spell is cast.
=> fix: prevent players from being able to disable shroud in capstones

ACE.sln.DotSettings, apps/server/Command/Handlers/AdminCommands.cs, apps/server/Entity/Fellowship.cs, apps/server/Entity/Landblock.cs, apps/server/WorldObjects/Player_Location.cs, apps/server/WorldObjects/Portal.cs, apps/server/WorldObjects/WorldObject_Properties.cs, libs/entity/Enum/Properties/PropertyBool.cs
Rework dungeon instancing system.
- Add flag FellowshipRequired that can be set on dungeon portals to require the player to be in a fellowship to enter.
- Capstone dungeon landblocks now keep track of the first fellowship that enters them.
- Players of the fellowship will be placed in the same instance when entering a capstone dungeon.
- Players in a different fellowship will be placed in the first available inactive instance.
- If there are no inactive instances available, player will receive a message and be teleported to their "sanctuary" (LS).
- Leaving the fellowship instantly teleports the player back to their "sanctuary".
- Dungeons unload after 5 minutes "dormant" (no players inside).
- Adjusted code for admin command '/capstone <name>' to show how long the dungeon has been …
=> feat: update dungeon instancing system

ACE.sln.DotSettings, apps/server/Entity/DamageEvent.cs, apps/server/WorldObjects/Creature_Combat.cs, apps/server/WorldObjects/Player_Combat.cs, apps/server/WorldObjects/SpellProjectile.cs, apps/server/WorldObjects/WorldObject_Weapon.cs
Major refactor of the DamageEvent class.
- Convert unnecessary public variables to private.
- Encapsulate public variables and prevent write access.
- Reorganize member variables.
- Refactor DoCalculateDamage() method from ~800 to ~35 lines by dividing it into smaller fucntions, making it more readable.
- Attempt to move all CombatAbility/SpecialRating/SkillSpec bonuses into their own functions.
- Various other tweaks and adjustments.
=> refactor: DamageEvent

apps/server/Entity/DamageEvent.cs, apps/server/WorldObjects/Jewel_Bonuses.cs, apps/server/WorldObjects/SpellProjectile.cs, apps/server/WorldObjects/WorldObject_Magic.cs
- Use less convoluted divisor for ramp rating calculations. (50 instead of 66).
- Change to multiplication instead of division for easier reading (x/50 to x*0.02f)
- Refactor formulas for easier reading.
- Add more information to summaries.
=> feat: rebalance ramping rating calculations

apps/server/WorldObjects/Creature_Death.cs
Currently gives rewards to lone shrouded players. Unsure if we'll be using this functionality anyways but would like to leave it available to re-enable.
=> feat: temporarily disable HandleShroudRewards

apps/server/Network/Structure/AppraiseInfo.cs, apps/server/WorldObjects/Jewel_Bonuses.cs
- Disable client AppraisalLongDescDecoration functionality.
- Add custom functionality that mimics decoration text, but also allows custom text to used in the Long Desc of items.
- Add an 'Additional Properties' field to the Use text field, that displays a list of each special ratings (jewel effects) an item has.
- Add a 'Property Descriptions' field to the LongDesc text field, that displays descriptions of each special rating an item has.
- Fix some typos and formatting in the Jewel_Bonuses class.
=> Additional properties appraise info

apps/server/Factories/LootGenerationFactory_Caster.cs, apps/server/Factories/LootTables.cs, apps/server/Network/Structure/AppraiseInfo.cs, apps/server/WorldObjects/Creature_Properties.cs, apps/server/WorldObjects/WorldObject_Weapon.cs
- Display all special (non-retail) ratings in the "Additional Properties" list, when appraising an item.
- Add a new "Property Descriptions" field near the bottom of the appraise window that displays details about every special property on the item.
- (imbues, jewel effects, etc)
- Refactor the AppraiseInfo class.
=> feat: add special property descriptions on items

apps/server/Entity/DamageEvent.cs, apps/server/Entity/Spell.cs, apps/server/Network/Structure/AppraiseInfo.cs, apps/server/WorldObjects/Creature_Equipment.cs, apps/server/WorldObjects/Creature_Melee.cs, apps/server/WorldObjects/Creature_Rating.cs, apps/server/WorldObjects/Hotspot.cs, apps/server/WorldObjects/Jewel_Bonuses.cs, apps/server/WorldObjects/Monster_Awareness.cs, apps/server/WorldObjects/Player_Melee.cs, apps/server/WorldObjects/Player_Missile.cs, apps/server/WorldObjects/Player_Tick.cs, apps/server/WorldObjects/Player_Xp.cs, apps/server/WorldObjects/SpellProjectile.cs, apps/server/WorldObjects/WorldObject.cs, apps/server/WorldObjects/WorldObject_Magic.cs, apps/server/WorldObjects/WorldObject_Weapon.cs, libs/entity/Enum/Properties/PropertyBool.cs
- New bool: SpecialPropertiesRequireMana.
- If bool is true, the item must have mana for all special properties to activate. (imbues, ratings, etc)
- To be used with quest gear items mostly.
=> feat: option for items to require having mana to activate properties

apps/server/Entity/Confirmation.cs, apps/server/WorldObjects/SpellTransference.cs, apps/server/WorldObjects/WorldObject.cs, apps/server/WorldObjects/WorldObject_Properties.cs, libs/entity/Enum/Properties/PropertyBool.cs, libs/entity/Enum/Properties/PropertyInt.cs
- Extracting: Rather than selecting a random spell, cycle through each spell when player selects "No", allowing players to easily target a spell to extract.
- Transferring: Provide preview of potential new arcane lore requirement on confirmation box.
=> feat: improve pearl of transference

apps/server/Entity/Confirmation.cs, apps/server/Factories/WorldObjectFactory.cs, apps/server/WorldObjects/SpellPurge.cs, apps/server/WorldObjects/SpellTransference.cs, libs/entity/Enum/WeenieType.cs
- Can be used on gear with spells to remove a target spell without destroying the item. 
- Recalculates arcane lore activation requirement.
- Consumes 1 pearl per target item tier.
- Pearl of Spell Transference also adjusted to cost 1 pearl per target item tier.
=> feat: add pearl of spell purging item

apps/server/WorldObjects/WorldObject_Magic.cs
- Set target to self for shielding scarab spell effect.
- Prevent other possible null references for spell effects without a target.
=> fix: set target for shielding scarab when using non-targeting spells

apps/server/WorldObjects/Managers/EmoteManager.cs
- Rather than always deleting an entire stack, force the DeleteSelf emote to remove a single object if an item stack size is greater than one.
=> feat: allow deleteself emote to remove 1 object from a stack

apps/server/Entity/GeneratorProfile.cs, apps/server/Factories/LootGenerationFactory.cs, apps/server/Factories/Tables/Wcids/Weapons/AtlatlWcids.cs, apps/server/Factories/Tables/Wcids/Weapons/ThrownWcids.cs, apps/server/Factories/Tables/WeaponTypeChance.cs
- Warrior Profiles: remove bow/crossbow/ataltl/staff, add thrown.
- Rogue Profiles: remove thrown, add staff.
- In chest loot, consolidate all stackable items of the same WCID.
=> feat: update some loot gen categories and consolidate stackables

apps/server/WorldObjects/Creature_Equipment.cs, apps/server/WorldObjects/EmpoweredScarab.cs, apps/server/WorldObjects/Hotspot.cs, apps/server/WorldObjects/Managers/ConfirmationManager.cs, apps/server/WorldObjects/Managers/EmoteManager.cs, apps/server/WorldObjects/Player_EmpoweredScarab.cs
- Upon entering a mana field hot spot, server checks if there are any equipped/held mana scarabs that can be recharged or altered.
- If there are, a confirmation box will appear, describing the effects of the current menhir ring. Selecting 'Yes' will force the player into a mediation emote and begin charging scarabs.
- If there aren't, a transient error message will appear notifying the player that they do not have any scarabs that can interact with the menhir ring at the moment.
=> feat: improve menhir mana field interactions

apps/server/Managers/PropertyManager.cs, apps/server/WorldObjects/Player_Death.cs
- Ensure buffs from items/foci are not lost on death.
- Add server property that can prevent players from having corpses on death (no items dropped).
=> Player death fixes

apps/server/WorldObjects/Player_Inventory_Banking.cs, apps/server/WorldObjects/Player_Tracking.cs, apps/server/WorldObjects/Storage.cs, apps/server/WorldObjects/WorldObject.cs
- Remove BankChests from the bank list when a bank is unloaded from a landblock.
- Ensure golem translucency is always visible when generated.
- Fix various bank log formats.
=> fix: banking improvements

apps/server/starterGear.json
Potentially will be reintroduced when revised. Or come up with a better way to explain new mechanics in-game.
=> feat: remove starter guide books

apps/server/WorldObjects/Creature_Death.cs, apps/server/WorldObjects/Player_Xp.cs
- Disable "Maximum xp per kill" rule. (may need to re-enable if power-leveling is too abusable)
- Adjust "Over-level Penalties":
- Allow it to apply to quests as well, if quest has a 'source level' set. (not set on any quests atm)
- Increase the penalty when a player has reached the 'soft_level_cap', from 10% to 50% per level difference.
- Reword some variables and add some null reference checks.
=> Revise xp rules

apps/server/Entity/SigilTrinketEvent.cs, apps/server/Factories/LootGenerationFactory_SigilTrinket.cs, apps/server/WorldObjects/Player_Combat.cs, apps/server/WorldObjects/Player_SigilTrinket.cs, apps/server/WorldObjects/SigilTrinket.cs
- Might: Health-based sigil trinket with two-hand/shield reqs. Chance to convert a normal hit into a crit while attacking at greater than 50% power.
- Aggression" Health-based sigil trinket with two-hand/shield reqs. Chance to add additional threat to your target while attacking greater than 50% power.
=> feat: add Might and Aggression sigil trinkets

apps/server/Entity/DamageEvent.cs, apps/server/Entity/SigilTrinketEvent.cs, apps/server/Factories/LootGenerationFactory_SigilTrinket.cs, apps/server/WorldObjects/Player_Combat.cs, apps/server/WorldObjects/SigilTrinket.cs
- Assailment: Stamina-based sigil trinket with dual wield req. Chance on critical hit to gain a damage buff for 10 seconds.
- Treachery: Stamina-based sigil trinket with sneak attack req. Chance on sneak attack critical hit to deal double critical damage.
=> feat: add Assailment and Treachery sigil trinkets

apps/server/Entity/SigilTrinketEvent.cs, apps/server/Factories/LootGenerationFactory_SigilTrinket.cs, apps/server/WorldObjects/Monster_Awareness.cs, apps/server/WorldObjects/Player_Ability.cs, apps/server/WorldObjects/Player_Combat.cs, apps/server/WorldObjects/SigilTrinket.cs, libs/entity/Enum/SpellCategory.cs, libs/entity/Enum/SpellId.cs
- Exposure: Stamina/Mana-based sigil trinket with perception req. Chance on successful Expose Weakness to gain a damage buff for 10 sec.
- Avoidance: Stamina/Mana-based sigil trinket with deception req. Chance on power attack to generate no threat towards the target.
- Also fix some text and add new buff spells.
- SigilTrinketCriticalChanceBoost, SigilTrinketCriticalDamageBoost, SigilTrinketDamageBoost.
=> feat: add Exposure and Avoidance sigil trinkets

apps/server/Command/Handlers/DeveloperCommands.cs, apps/server/Factories/LootGenerationFactory.cs, apps/server/Factories/Tables/WorkmanshipChance.cs, apps/server/Factories/WorldObjectFactory.cs, apps/server/Network/Structure/AppraiseInfo.cs, apps/server/WorldObjects/Creature.cs, apps/server/WorldObjects/Creature_Death.cs, apps/server/WorldObjects/Managers/EmoteManager.cs, apps/server/WorldObjects/Player_Inventory.cs, apps/server/WorldObjects/WorldObject_Properties.cs, libs/entity/Enum/Properties/PropertyInt.cs
- Trophies can now receive a quality level mutation when generated, depending on tier of the killed enemy.
- The trophy receives an adjective to its name and mutated value based on quality level.
- There are 10 unique adjectives. (i.e. an Armoredillo Hide could be "Crude", "Excellent", "Peerless", etc.)
- When presenting a trophy to a collector/npc, using the Refuse emote and YesNo confirmation, The confirmation box can display the name of the item and the proposed pyreal value from the NPC.
- If a player accepts the NPCs offer, the TakeItems emote can now take a specific GUID rather than just the first matching WCID in the player inventory. This allows the correct trophy to be taken if a player is holding different quality levels of the same trophy type.
- TODO: for NPCs that offer items …
=> feat: implement improved trophy system

apps/server/Entity/Fellowship.cs, apps/server/WorldObjects/Player_Fellowship.cs
- Prevent fellowships from being disbanded if any party member is in a FellowshipRequired landblock.
- Give players 1 minute to rejoin a fellowship if quit or dismissed in a FellowshipRequired landblock, before teleporting them to their sanctuary position.
=> feat: add safety measures to fellowship landblock booting

apps/server/WorldObjects/Portal.cs, apps/server/WorldObjects/WorldObject_Magic.cs
- Players can no longer enter a summoned gateway of a FellowshipRequired portal without being in a fellowship.
- Players can now tie to and summon FellowshipRequired portals without being in a fellowship.
=> feat: Adjust logic for portal spells with FellowshipRequired portals

apps/server/Factories/Tables/VendorBaseItems.cs, apps/server/WorldObjects/Managers/EmoteManager.cs, apps/server/WorldObjects/SpellPurge.cs, apps/server/WorldObjects/SpellTransference.cs, apps/server/WorldObjects/UpgradeKit.cs
- Add some of the capstone rewards to vendors.
- Pearl of Spell Transference to Archmages.
- Pearl of Spell Purging to Archmages.
- Upgrade Kits to Blacksmiths/Armorers/Weaponsmiths.
- Add Pearl of Spell Purging to capstone rewards.
- Tweak Capstone reward amounts.
- Increase number of pearls and upgrade kits required for crafting interactions.
=> feat: update capstone rewards

apps/server/WorldObjects/Player_Skills.cs, apps/server/WorldObjects/Scroll.cs
- For scrolls that require magic specialization, display the correct error message if player's skill is too low.
=> fix: set correct read scroll messages

apps/server/Factories/LootGenerationFactory_Caster.cs, apps/server/Factories/LootGenerationFactory_Melee.cs, apps/server/Factories/LootGenerationFactory_Missile.cs, apps/server/Factories/LootGenerationFactory_Spells.cs, apps/server/WorldObjects/Player_Inventory.cs, apps/server/WorldObjects/SpellTransference.cs
- Client seems to use wield difficulty 1 and 2 to display a "Training required" message on gear. We were previously assigning diff 1 to lootgen gear for training req when we should've be assigning diff 2.
- Lootgen now assigns correct diff 2 for training wield reqs.
- Previously obtained loot with trained wield reqs will be equippable without trained skill.
=> fix: adjust wield req training checks

apps/server/WorldObjects/Jewel_Bonuses.cs
- Needed to divide the rating by 100.
=> fix: opal jewel proc rate

apps/server/Entity/LevelScaling.cs
- Add a mod that reduces the effects of level scaling when a player's level is towards the end of their current tier.
- Currently assumes a player can achieve ~50% progress towards the next tier in stats by the time they reach the next tier. May need to be adjusted after testing.
=> feat: improve level scaling accuracy

apps/server/Entity/AllegianceNode.cs
Allow players to start at rank 1 as a baseline.
=> feat: update allegiance rank calculation

apps/server/WorldObjects/WorldObject_Magic.cs
- Pass correct modifier for Nullification jewel mod.
- Make Selflessness, HealBubble, and TransferPenalty jewel mods only affect helpful boost spells.
- Make Nullficiation jewel mod only affect harmful boost spells.
=> fix: boost spell jewel mods

apps/server/WorldObjects/Creature_Properties.cs, apps/server/WorldObjects/Player_Combat.cs, apps/server/WorldObjects/Player_Skills.cs
- Now acts as a multiplier, reducing damage by up to an additional 20%.
- Uses "Current" Str+End attribute amounts so that those buffs are desired for maximum damage reduction.
- Starts at 200 Str+End (0%) and caps at 600 (20%).
- Effects all damage types equally.
=> feat: rework natural resistance

apps/server/WorldObjects/SpellTransference.cs
- Correctly add new spell after removing old spell.
- Display correct potential arcane lore in confirmation box.
- Add a skill icon to the pearl with an extracted spell.
=> fix: spell transfer upgrade spell

apps/server/WorldObjects/SpellProjectile.cs, apps/server/WorldObjects/WorldObject_Magic.cs
- Monster spell casting is now affected by the lethality archetype.
- Boost and Transfer spells are now affected by attribute mod (self).
=> feat: monster lethality and attribute mod for life

apps/server/Entity/DamageEvent.cs, apps/server/Entity/LevelScaling.cs
- Add AvgTimeToKill factor based on data for different tiers.
- Increases damage of higher level payers when being scaled down to lower levels.
- Example: will increase damage that a level 50 deals vs a level 10 by 50% (when shrouded).
=> feat: improve level scaling formula

apps/server/Entity/DamageEvent.cs, apps/server/Managers/RecipeManager.cs, apps/server/Network/Structure/AppraiseInfo.cs, apps/server/WorldObjects/Ammunition.cs, apps/server/WorldObjects/Player_Missile.cs, libs/entity/Enum/Properties/PropertyInt.cs
- Woodworkers can use an Intricate Carving tool on ammo to give it a 10% damage bonus for a limited number of uses. Requires sufficient woodworking skill for each ammo wield tier.
- More "ammo effect" recipes to come.
=> feat: add sharpen ammo crafting for woodworking

apps/server/Entity/StaminaTable.cs, apps/server/WorldObjects/Player_Missile.cs
-  Additionally, slightly reduce stamina costs of all melee/missile attacks.
=> fix: set correct animation length for calculating missile stamina usage

apps/server/Entity/DamageEvent.cs, apps/server/Entity/LevelScaling.cs, apps/server/WorldObjects/Creature_ArchetypeSystem.cs, apps/server/WorldObjects/SpellProjectile.cs
- Prevents higher level players from receiving dramatically more damage than lower level players when being scaled down to a low level.
- Additionally, smoothened out dps per tier curve for archetype system.
=> feat: add xDpsPerTier factor to level scaling formula

apps/server/Factories/Tables/Cantrips/CantripChance.cs
- t3: Minor = 75%, Major = 25%.
- t4: Minor = 50%, Major = 50%.
- t5: Minor = 25%, Major = 74%, Epic = 1%.
- t6 Major = 75%, Epic = 25%.
- t7: Major = 50%, Epic = 49%, Leg = 1%.
=> fix: cantrip level chances for t3+

apps/server/Factories/Tables/WeaponTypeChance.cs
- Heritage drop rates raised to be equal with missile weapons. (from 1/3rd)
- Thrown Weapons drop rates raised to be half of marital weapons (from 1/4th).
=> feat: update weapon type chances

apps/server/WorldObjects/Player_Location.cs
- Instead of placing player at the beginning of the dungeon, send them to sanctuary position.
=> feat: send players to sanctuary after reconnecting while in a capstone

apps/server/Entity/SigilTrinketEvent.cs
- Prevent trinket from triggering if there are no remaining uses.
- Prevent effects from a different trinket from firing when more than one trinket is equipped.
=> fix; sigil trinket issues

apps/server/Entity/Landblock.cs, apps/server/WorldObjects/Storage.cs
- Reload bank object on close to prevent caching issues.
- Always set bank encumbrance and value to 0 during bank transactions.
=> fix: reload bank object on close

libs/entity/Models/WeenieExtensions.cs
Allow pearls, upgrade kits, and armor patches to be purchased as stacks with only 1 backpack slot available.
=> feat: add custom stackables for vendor transactions

apps/server/WorldObjects/Creature_Navigation.cs, apps/server/WorldObjects/Monster_Navigation.cs, apps/server/WorldObjects/Monster_Tick.cs
- When a monster tries to return to their home location, they now fully heal instantly.
- If a monster is attempting to melee attack a player and doesn't land an attack within 10 seconds, they will move to their home location and heal.
=> feat: update monster MoveToHome mechanics

apps/server/WorldObjects/Hotspot.cs, apps/server/WorldObjects/WorldObject.cs, libs/entity/Enum/Properties/PropertyBool.cs
- Allow creatures with the setting enabled to reset when they enter an AI hotspot.
- Upon reset, creature full heals and runs to home position.
=> feat: add monster boundary system

apps/server/Network/Structure/AppraiseInfo.cs, apps/server/WorldObjects/Player_Inventory.cs, apps/server/WorldObjects/Player_Magic.cs, apps/server/WorldObjects/WorldObject_Properties.cs, libs/entity/Enum/Properties/PropertyInt.cs
- Casters with this setting enable can cast spells of a specific school without the need for spell components.
- Spells from other schools cannot be cast.
=> feat: add magic school primacy affix

apps/server/Factories/LootGenerationFactory.cs, apps/server/Factories/LootGenerationFactory_Clothing.cs, apps/server/WorldObjects/UpgradeKit.cs
- Rather than doing a +/- 10% variance on mutation, allow armor and ward to roll between the base amount of the current tier and the base amount of the next tier. (with diminishing chances for a high roll)
- Update Upgrade Kit logic to reflect this change.
=> feat: adjust how AL and WL mutate

apps/server/Entity/DamageEvent.cs, apps/server/Factories/LootGenerationFactory_Melee.cs, apps/server/Factories/LootGenerationFactory_Missile.cs, apps/server/WorldObjects/Player_Combat.cs, apps/server/WorldObjects/Player_Melee.cs
- Cleave hits deal 50% damage to additional targets.
- Lootgen Cleavers no longer have damage reduced to 60% upon generation.
- Also update base anim speed mod for lootgen weapon factory.
=> feat: overhaul cleave mechanic

apps/server/WorldObjects/Managers/EmoteManager.cs
- If ObjCellId is left NULL, the TeleportTarget emote will use the current cell instead.
=> feat: add option to teleport target within current cell 

apps/server/Factories/LootGenerationFactory.cs, apps/server/WorldObjects/UpgradeKit.cs
- Allow items with Resto mod (but not elemental damage mod) to mutate properly.
- Allow items with Resto mod to upgrade properly when using an upgrade kit.
=> feat: add quest mutation support for resto mod

apps/server/Entity/DamageEvent.cs, apps/server/WorldObjects/Jewel_Bonuses.cs
- Ensure Self Harm jewel effect defaults to 1.0 multiplier.
- Prevent null reference when applying melee ramp stamps while unarmed.
=> fix: jewel related errors

apps/server/WorldObjects/Jewel_Bonuses.cs
Also change "Fury" jewels to weapon or armor, instead of weapon+shield  or armor.
=> fix: amber jewel socket targets

apps/server/WorldObjects/Player_Ability.cs
When swapping from Overload <-> Battery or from Fury <-> Relentless, lose half of built up Mana Charge or Adrenaline.
=> feat: lose 50% build-up on stance swap

apps/server/WorldObjects/Creature_Combat.cs, apps/server/WorldObjects/SkillFormula.cs
Now based on shield level vs attacker attack skill.
- When both are equal, provides 25% damage reduction.
- Caps at 50%.
- Minimum 0%.
=> feat: rework shield damage reduction calculation

apps/server/WorldObjects/Creature_ArchetypeSystem.cs
- Use the same % damage dealt formulas for all tiers when calculating monster damage, if they are enemies that utilize nearby-player-scaling. (this effects all capstone monsters and some overland monsters such as ON).
- The result will increase damage of lower level capstone monsters substantially, bringing them on par with level 50 capstone monsters. Level 50 capstones will not see a change.
=> feat: make all capstones similar difficulty, regardless of tier
